//! Purpose:
//! PHP golden fixtures for the elephc-crypto openssl cipher engine
//! (`openssl_encrypt` / `openssl_decrypt` parity). Generated by
//! `crates/elephc-crypto/tests/gen_openssl_fixtures.php` — do not edit by hand.
//!
//! Called from:
//! - Included by `crates/elephc-crypto/tests/openssl_php_fixtures.rs` and the
//!   phase 1 cipher ABI tests.
//!
//! Key details:
//! - Baselined against PHP 8.4.19 with OpenSSL 3.6.1 27 Jan 2026 (local CLI).
//!   Repository CI does not pin or provision PHP; checked-in values are the CI
//!   baseline, and regeneration is an explicit version-stamped operation.
//! - All vectors use OPENSSL_RAW_DATA semantics: ciphertext/tag bytes are raw
//!   (hex-encoded here). Base64 handling lives in the PHP glue layer, and the
//!   one base64-mode golden string below pins it.
//! - Locked PHP quirks (observed on PHP 8.4.19):
//!   - empty or short CBC/CTR IV is zero-padded to the cipher IV length; long
//!     IV is truncated. Encrypt warns for all three cases; decrypt warns for
//!     short/long IV but not an empty IV. Both results and warning strings are
//!     captured in `IV_NORMALIZATION_VECTORS`;
//!   - short key is zero-padded to the key length unless
//!     OPENSSL_DONT_ZERO_PAD_KEY (then the call fails); long key is truncated;
//!   - GCM accepts any non-empty IV length (it must match between encrypt and
//!     decrypt); empty GCM IV fails;
//!   - GCM encrypt tag_length range is 1..=16; decrypt compares only the first
//!     `tag.len()` bytes of the expected tag;
//!   - OPENSSL_ZERO_PADDING requires block-aligned plaintext on encrypt and
//!     strips nothing on decrypt (CBC/ECB only; ignored by CTR);
//!   - cipher names are matched case-insensitively (uppercase vector below).
//! - Plaintexts: PT43 = "The quick brown fox jumps over the lazy dog" (43
//!   bytes, non-block-aligned), PT16/PT32 = "0123456789abcdef" repeated.

/// PHP version the fixtures were baselined against.
pub const FIXTURE_PHP_VERSION: &str = "8.4.19";

/// OpenSSL implementation the fixture-generating PHP executable used.
pub const FIXTURE_OPENSSL_VERSION: &str = "OpenSSL 3.6.1 27 Jan 2026";

/// 43-byte non-block-aligned plaintext used across the matrix vectors.
pub const PT43: &str = "The quick brown fox jumps over the lazy dog";

/// One-block plaintext used by zero-padding decrypt checks.
pub const PT16_HEX: &str = "30313233343536373839616263646566";

/// One encrypt vector against the PHP golden output for a fixed key/IV/AAD.
pub struct CipherVector {
    pub cipher: &'static str,
    pub key_hex: &'static str,
    pub iv_hex: &'static str,
    pub aad_hex: &'static str,
    pub ciphertext_hex: &'static str,
    pub tag_hex: &'static str,
    pub tag_length: usize,
}

/// One vector per supported non-AEAD cipher plus GCM with and without AAD
/// (GCM ciphertext is AAD-independent; the tag is not).
pub static CIPHER_VECTORS: &[CipherVector] = &[
    CipherVector {
        cipher: "aes-128-cbc",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "69696969696969696969696969696969",
        aad_hex: "",
        ciphertext_hex: "835efdd4ef3b4970b9f3db30d9127055f882c14e350482e2dbb2d280a3a88f6db7268c07781eaef8c5bb68f682c1ccfe",
        tag_hex: "",
        tag_length: 16,
    },
    CipherVector {
        cipher: "aes-192-cbc",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "69696969696969696969696969696969",
        aad_hex: "",
        ciphertext_hex: "7f1fe73ee521844a8b46dc977e46874678a51a3cd0c9c1eaa05c205a0c00e165e2b56de56b3de6d230d53f1e4f7c1a0c",
        tag_hex: "",
        tag_length: 16,
    },
    CipherVector {
        cipher: "aes-256-cbc",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "69696969696969696969696969696969",
        aad_hex: "",
        ciphertext_hex: "be31f07a2f667bf34754e8ec45bb2682bf31f430dcb303ab089a7ad13ce938260b555d72f8a714145e43af7cb50a21e1",
        tag_hex: "",
        tag_length: 16,
    },
    CipherVector {
        cipher: "aes-128-ecb",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "",
        aad_hex: "",
        ciphertext_hex: "68eebf6de918e9e1477707a12f5dafffd04584d292c5f148b544ff0f0583d192204b10b71ea89be7460b29f617a5fd47",
        tag_hex: "",
        tag_length: 16,
    },
    CipherVector {
        cipher: "aes-192-ecb",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "",
        aad_hex: "",
        ciphertext_hex: "d3040c8b0ca3c82b183939dcc25b1556acf172ad850be4639d2e78c1902697284ee72046aa5ca058b5c0dc44ef422d1f",
        tag_hex: "",
        tag_length: 16,
    },
    CipherVector {
        cipher: "aes-256-ecb",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "",
        aad_hex: "",
        ciphertext_hex: "e17e9c1f4520d16e0ec019104b5ea547c1db79d9150e5cd0e1a560d25de5ee07ef2fe580b630ff109d96573c8bc009ba",
        tag_hex: "",
        tag_length: 16,
    },
    CipherVector {
        cipher: "aes-128-ctr",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "69696969696969696969696969696969",
        aad_hex: "",
        ciphertext_hex: "08d99fdf922e2adbe101aaa3c7cfc07e74a400fda2fbe6e2950f91bca86d3a13901d927eb1a414f2f7530a",
        tag_hex: "",
        tag_length: 16,
    },
    CipherVector {
        cipher: "aes-192-ctr",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "69696969696969696969696969696969",
        aad_hex: "",
        ciphertext_hex: "8d2556a19a8f13cfa2569e7de40a7ccaa9d5c2b885b7840afe938fc424c4afe600561aaba5859473eebd0c",
        tag_hex: "",
        tag_length: 16,
    },
    CipherVector {
        cipher: "aes-256-ctr",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "69696969696969696969696969696969",
        aad_hex: "",
        ciphertext_hex: "4ed947c17245c2403b7f3bbc62aa3ea7c495c675da80902be67c78d801659339c0c7d00344365121b8fbf0",
        tag_hex: "",
        tag_length: 16,
    },
    CipherVector {
        cipher: "aes-128-gcm",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "696969696969696969696969",
        aad_hex: "666978747572652d616164",
        ciphertext_hex: "498c432b6dc88827705706a39e646b6a0698aa89834fb084768c9c416f758018ccc5ae865bc43a1db8b91a",
        tag_hex: "bec1dfa8e8781396a92dc401358ee08c",
        tag_length: 16,
    },
    CipherVector {
        cipher: "aes-128-gcm",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "696969696969696969696969",
        aad_hex: "",
        ciphertext_hex: "498c432b6dc88827705706a39e646b6a0698aa89834fb084768c9c416f758018ccc5ae865bc43a1db8b91a",
        tag_hex: "ac86d357795c8d75dbd16e67933c0c3d",
        tag_length: 16,
    },
    CipherVector {
        cipher: "aes-192-gcm",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "696969696969696969696969",
        aad_hex: "666978747572652d616164",
        ciphertext_hex: "4213f3f4708cef7d03ac167c8487ec43b14e740e0f0ea458b41ae4eca28cb9cb46d24ec873f24e40010cf5",
        tag_hex: "f9ebd39bfa23886420d8a159d50f4dad",
        tag_length: 16,
    },
    CipherVector {
        cipher: "aes-192-gcm",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "696969696969696969696969",
        aad_hex: "",
        ciphertext_hex: "4213f3f4708cef7d03ac167c8487ec43b14e740e0f0ea458b41ae4eca28cb9cb46d24ec873f24e40010cf5",
        tag_hex: "845ca1bc50e43231a4bcd5773ae2ad55",
        tag_length: 16,
    },
    CipherVector {
        cipher: "aes-256-gcm",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "696969696969696969696969",
        aad_hex: "666978747572652d616164",
        ciphertext_hex: "8eec9d54438dc8679074830af4604b47f4cb062a754edb3c561d21b76dbac62b6fd7b2c040ca67e3e5647a",
        tag_hex: "9dc8b5e7b800bfed5c1be43fc4614f51",
        tag_length: 16,
    },
    CipherVector {
        cipher: "aes-256-gcm",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "696969696969696969696969",
        aad_hex: "",
        ciphertext_hex: "8eec9d54438dc8679074830af4604b47f4cb062a754edb3c561d21b76dbac62b6fd7b2c040ca67e3e5647a",
        tag_hex: "b01111a9309dcc1b617c54ffe3b8ce58",
        tag_length: 16,
    },
];

/// GCM encrypt with truncated tags: ciphertext equals the tag_length=16
/// vector; the tag is its first `tag_length` bytes.
pub struct TagLengthVector {
    pub tag_length: usize,
    pub ciphertext_hex: &'static str,
    pub tag_hex: &'static str,
}

/// aes-256-gcm encrypt of PT43 (key/IV/AAD as the matching CIPHER_VECTORS
/// entry) with non-default tag lengths.
pub static GCM_TAG_LENGTH_VECTORS: &[TagLengthVector] = &[
    TagLengthVector { tag_length: 1, ciphertext_hex: "8eec9d54438dc8679074830af4604b47f4cb062a754edb3c561d21b76dbac62b6fd7b2c040ca67e3e5647a", tag_hex: "9d" },
    TagLengthVector { tag_length: 4, ciphertext_hex: "8eec9d54438dc8679074830af4604b47f4cb062a754edb3c561d21b76dbac62b6fd7b2c040ca67e3e5647a", tag_hex: "9dc8b5e7" },
    TagLengthVector { tag_length: 12, ciphertext_hex: "8eec9d54438dc8679074830af4604b47f4cb062a754edb3c561d21b76dbac62b6fd7b2c040ca67e3e5647a", tag_hex: "9dc8b5e7b800bfed5c1be43f" },
];

/// AES-256-GCM encrypt result for a non-default, non-empty IV length.
pub struct GcmIvVector {
    pub iv_hex: &'static str,
    pub ciphertext_hex: &'static str,
    pub tag_hex: &'static str,
}

/// PHP goldens proving that GCM accepts short and long non-empty IVs.
pub static GCM_NON_DEFAULT_IV_VECTORS: &[GcmIvVector] = &[
    GcmIvVector { iv_hex: "69", ciphertext_hex: "4650f3e8588821e88d8520806652868affbf83700cbb75214a352e27a62aaab2bc15ff691d08199fb93f36", tag_hex: "eeaf537ddcc7aeb58c028ba3fda3a82b" },
    GcmIvVector { iv_hex: "69696969696969696969696969696969", ciphertext_hex: "058c1967af117fc4142b6c851c3ca083c65b71f3c28d9041a8247fc5f3070afb513839a2043457948c44b6", tag_hex: "69490efb2851c5a47142b09f074b143e" },
    GcmIvVector { iv_hex: "6969696969696969696969696969696969696969", ciphertext_hex: "2acd01597f93c67ad2a8d8dbfce769e144c81902f9020789c7fe0aec87a0e30310564eda5b3c90afc899f2", tag_hex: "08d4b454da863bc3456d8bdbe4b557e2" },
];

/// One successful CBC/CTR round-trip with a normalized IV and captured PHP
/// warnings for both encrypt and decrypt.
pub struct IvNormalizationVector {
    pub case: &'static str,
    pub cipher: &'static str,
    pub key_hex: &'static str,
    pub iv_hex: &'static str,
    pub plaintext_hex: &'static str,
    pub ciphertext_hex: &'static str,
    pub encrypt_warning: &'static str,
    pub decrypt_warning: &'static str,
}

/// Empty, short, and long IV behavior for both CBC and CTR.
pub static IV_NORMALIZATION_VECTORS: &[IvNormalizationVector] = &[
    IvNormalizationVector {
        case: "empty",
        cipher: "aes-256-cbc",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "",
        plaintext_hex: "54686520717569636b2062726f776e20666f78206a756d7073206f76657220746865206c617a7920646f67",
        ciphertext_hex: "e17e9c1f4520d16e0ec019104b5ea547f0f3dfcfa25a8b813c3abf951dd8506e462b38a791415c8fcc3f56e357502a55",
        encrypt_warning: "openssl_encrypt(): Using an empty Initialization Vector (iv) is potentially insecure and not recommended",
        decrypt_warning: "",
    },
    IvNormalizationVector {
        case: "short",
        cipher: "aes-256-cbc",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "616263",
        plaintext_hex: "54686520717569636b2062726f776e20666f78206a756d7073206f76657220746865206c617a7920646f67",
        ciphertext_hex: "48cb74713de870fe0e5dfce84ed4498d1a40787c30bcd66ed9f14bbc37738643d344c3042b7616fcb7f119eb3eff8a72",
        encrypt_warning: "openssl_encrypt(): IV passed is only 3 bytes long, cipher expects an IV of precisely 16 bytes, padding with \\0",
        decrypt_warning: "openssl_decrypt(): IV passed is only 3 bytes long, cipher expects an IV of precisely 16 bytes, padding with \\0",
    },
    IvNormalizationVector {
        case: "long",
        cipher: "aes-256-cbc",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "6161616161616161616161616161616161616161",
        plaintext_hex: "54686520717569636b2062726f776e20666f78206a756d7073206f76657220746865206c617a7920646f67",
        ciphertext_hex: "140833b120e1faecb3ff52ba58aa683f18a9ba042a2b94fb4ec690c365d9effc64647f793d117b620d5d08125e70ca19",
        encrypt_warning: "openssl_encrypt(): IV passed is 20 bytes long which is longer than the 16 expected by selected cipher, truncating",
        decrypt_warning: "openssl_decrypt(): IV passed is 20 bytes long which is longer than the 16 expected by selected cipher, truncating",
    },
    IvNormalizationVector {
        case: "empty",
        cipher: "aes-256-ctr",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "",
        plaintext_hex: "54686520717569636b2062726f776e20666f78206a756d7073206f76657220746865206c617a7920646f67",
        ciphertext_hex: "8aa92548f4b92874dbd7c62cc707e5c01ba5680094fb75f3a91357dd6a4d0e1a880bd0c5a6d56d1a4b7175",
        encrypt_warning: "openssl_encrypt(): Using an empty Initialization Vector (iv) is potentially insecure and not recommended",
        decrypt_warning: "",
    },
    IvNormalizationVector {
        case: "short",
        cipher: "aes-256-ctr",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "616263",
        plaintext_hex: "54686520717569636b2062726f776e20666f78206a756d7073206f76657220746865206c617a7920646f67",
        ciphertext_hex: "37a19a1ab756cd71278dc6b65b5a32be4827e77cca300524efe95c5fe0b2db69b187c43bf8c5ad9b23ab7c",
        encrypt_warning: "openssl_encrypt(): IV passed is only 3 bytes long, cipher expects an IV of precisely 16 bytes, padding with \\0",
        decrypt_warning: "openssl_decrypt(): IV passed is only 3 bytes long, cipher expects an IV of precisely 16 bytes, padding with \\0",
    },
    IvNormalizationVector {
        case: "long",
        cipher: "aes-256-ctr",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "6161616161616161616161616161616161616161",
        plaintext_hex: "54686520717569636b2062726f776e20666f78206a756d7073206f76657220746865206c617a7920646f67",
        ciphertext_hex: "5432876ac649a18e2047d9fb002832d3f14d145a3f2aaafb0cfc0e557eec12978cb4d51de2556523a799c2",
        encrypt_warning: "openssl_encrypt(): IV passed is 20 bytes long which is longer than the 16 expected by selected cipher, truncating",
        decrypt_warning: "openssl_decrypt(): IV passed is 20 bytes long which is longer than the 16 expected by selected cipher, truncating",
    },
];

/// A PHP call that is expected to return `false`, with raw byte inputs encoded
/// as hex. `warning` is empty when PHP emits no user-facing warning.
pub struct FailureVector {
    pub case: &'static str,
    pub operation: &'static str,
    pub cipher: &'static str,
    pub data_hex: &'static str,
    pub key_hex: &'static str,
    pub iv_hex: &'static str,
    pub options: u32,
    pub aad_hex: &'static str,
    pub tag_hex: &'static str,
    pub tag_length: usize,
    pub warning: &'static str,
}

/// Failure behavior observed through PHP's public return/warning surface.
pub static FAILURE_VECTORS: &[FailureVector] = &[
    FailureVector {
        case: "unknown_cipher_encrypt",
        operation: "encrypt",
        cipher: "not-a-cipher",
        data_hex: "54686520717569636b2062726f776e20666f78206a756d7073206f76657220746865206c617a7920646f67",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "69696969696969696969696969696969",
        options: 1,
        aad_hex: "",
        tag_hex: "",
        tag_length: 16,
        warning: "openssl_encrypt(): Unknown cipher algorithm",
    },
    FailureVector {
        case: "unknown_cipher_decrypt",
        operation: "decrypt",
        cipher: "not-a-cipher",
        data_hex: "63697068657274657874",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "69696969696969696969696969696969",
        options: 1,
        aad_hex: "",
        tag_hex: "",
        tag_length: 16,
        warning: "openssl_decrypt(): Unknown cipher algorithm",
    },
    FailureVector {
        case: "unknown_cipher_iv_length",
        operation: "iv_length",
        cipher: "not-a-cipher",
        data_hex: "",
        key_hex: "",
        iv_hex: "",
        options: 0,
        aad_hex: "",
        tag_hex: "",
        tag_length: 0,
        warning: "openssl_cipher_iv_length(): Unknown cipher algorithm",
    },
    FailureVector {
        case: "short_key_dont_zero_pad_encrypt",
        operation: "encrypt",
        cipher: "aes-256-cbc",
        data_hex: "54686520717569636b2062726f776e20666f78206a756d7073206f76657220746865206c617a7920646f67",
        key_hex: "73686f72746b6579",
        iv_hex: "69696969696969696969696969696969",
        options: 5,
        aad_hex: "",
        tag_hex: "",
        tag_length: 16,
        warning: "openssl_encrypt(): Key length cannot be set for the cipher algorithm",
    },
    FailureVector {
        case: "zero_padding_unaligned_encrypt",
        operation: "encrypt",
        cipher: "aes-256-cbc",
        data_hex: "54686520717569636b2062726f776e20666f78206a756d7073206f76657220746865206c617a7920646f67",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "69696969696969696969696969696969",
        options: 3,
        aad_hex: "",
        tag_hex: "",
        tag_length: 16,
        warning: "",
    },
    FailureVector {
        case: "zero_padding_misaligned_decrypt",
        operation: "decrypt",
        cipher: "aes-256-cbc",
        data_hex: "616263",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "69696969696969696969696969696969",
        options: 3,
        aad_hex: "",
        tag_hex: "",
        tag_length: 16,
        warning: "",
    },
    FailureVector {
        case: "invalid_pkcs7_decrypt",
        operation: "decrypt",
        cipher: "aes-256-cbc",
        data_hex: "78787878787878787878787878787878",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "69696969696969696969696969696969",
        options: 1,
        aad_hex: "",
        tag_hex: "",
        tag_length: 16,
        warning: "",
    },
    FailureVector {
        case: "gcm_empty_iv_encrypt",
        operation: "encrypt",
        cipher: "aes-256-gcm",
        data_hex: "54686520717569636b2062726f776e20666f78206a756d7073206f76657220746865206c617a7920646f67",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "",
        options: 1,
        aad_hex: "666978747572652d616164",
        tag_hex: "",
        tag_length: 16,
        warning: "openssl_encrypt(): Setting of IV length for AEAD mode failed",
    },
    FailureVector {
        case: "gcm_wrong_tag_decrypt",
        operation: "decrypt",
        cipher: "aes-256-gcm",
        data_hex: "8eec9d54438dc8679074830af4604b47f4cb062a754edb3c561d21b76dbac62b6fd7b2c040ca67e3e5647a",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "696969696969696969696969",
        options: 1,
        aad_hex: "666978747572652d616164",
        tag_hex: "78787878787878787878787878787878",
        tag_length: 16,
        warning: "",
    },
    FailureVector {
        case: "gcm_missing_tag_decrypt",
        operation: "decrypt",
        cipher: "aes-256-gcm",
        data_hex: "8eec9d54438dc8679074830af4604b47f4cb062a754edb3c561d21b76dbac62b6fd7b2c040ca67e3e5647a",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "696969696969696969696969",
        options: 1,
        aad_hex: "666978747572652d616164",
        tag_hex: "",
        tag_length: 0,
        warning: "",
    },
    FailureVector {
        case: "gcm_tag_length_0_encrypt",
        operation: "encrypt",
        cipher: "aes-256-gcm",
        data_hex: "54686520717569636b2062726f776e20666f78206a756d7073206f76657220746865206c617a7920646f67",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "696969696969696969696969",
        options: 1,
        aad_hex: "666978747572652d616164",
        tag_hex: "",
        tag_length: 0,
        warning: "openssl_encrypt(): Retrieving verification tag failed",
    },
    FailureVector {
        case: "gcm_tag_length_17_encrypt",
        operation: "encrypt",
        cipher: "aes-256-gcm",
        data_hex: "54686520717569636b2062726f776e20666f78206a756d7073206f76657220746865206c617a7920646f67",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "696969696969696969696969",
        options: 1,
        aad_hex: "666978747572652d616164",
        tag_hex: "",
        tag_length: 17,
        warning: "openssl_encrypt(): Retrieving verification tag failed",
    },
    FailureVector {
        case: "invalid_base64_decrypt",
        operation: "decrypt",
        cipher: "aes-256-cbc",
        data_hex: "252525",
        key_hex: "6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b",
        iv_hex: "69696969696969696969696969696969",
        options: 0,
        aad_hex: "",
        tag_hex: "",
        tag_length: 16,
        warning: "",
    },
];

/// `openssl_cipher_iv_length` results for the full matrix.
pub static IV_LENGTHS: &[(&str, usize)] = &[
    ("aes-128-cbc", 16),
    ("aes-192-cbc", 16),
    ("aes-256-cbc", 16),
    ("aes-128-ecb", 0),
    ("aes-192-ecb", 0),
    ("aes-256-ecb", 0),
    ("aes-128-ctr", 16),
    ("aes-192-ctr", 16),
    ("aes-256-ctr", 16),
    ("aes-128-gcm", 12),
    ("aes-192-gcm", 12),
    ("aes-256-gcm", 12),
];

/// Empty plaintext: AES-256-CBC pads to one full block.
pub const EMPTY_PT_CBC_CIPHERTEXT_HEX: &str = "5d11c49af18b4b3e482508362bd2c857";

/// Empty plaintext: AES-256-CTR ciphertext remains empty.
pub const EMPTY_PT_CTR_CIPHERTEXT_HEX: &str = "";

/// Empty plaintext: AES-256-GCM ciphertext remains empty.
pub const EMPTY_PT_GCM_CIPHERTEXT_HEX: &str = "";

/// Empty plaintext: AES-256-GCM still produces an authentication tag.
pub const EMPTY_PT_GCM_TAG_HEX: &str = "76a0e5a2ff64c6f1c8ee0f2c0f066c91";

/// AES-256-CBC with the 8-byte key "shortkey": PHP zero-pads the key to 32.
pub const SHORT_KEY_CIPHERTEXT_HEX: &str = "76beda96baf03d3f2f5c1d5ff97cf900035bb02bd528a983ff4b7deec3f29b573086853900ca152b912f44d441c38649";

/// AES-128-CBC with a 32-byte key: PHP truncates the key to 16.
pub const LONG_KEY_CIPHERTEXT_HEX: &str = "835efdd4ef3b4970b9f3db30d9127055f882c14e350482e2dbb2d280a3a88f6db7268c07781eaef8c5bb68f682c1ccfe";

/// AES-256-CBC with an empty IV: PHP zero-fills the IV to 16 bytes.
pub const EMPTY_IV_CIPHERTEXT_HEX: &str = "e17e9c1f4520d16e0ec019104b5ea547f0f3dfcfa25a8b813c3abf951dd8506e462b38a791415c8fcc3f56e357502a55";

/// AES-256-CBC with a 3-byte IV "abc": PHP zero-pads the IV to 16 bytes.
pub const SHORT_IV_CIPHERTEXT_HEX: &str = "48cb74713de870fe0e5dfce84ed4498d1a40787c30bcd66ed9f14bbc37738643d344c3042b7616fcb7f119eb3eff8a72";

/// AES-256-CBC with a 20-byte IV: PHP truncates the IV to 16 bytes.
pub const LONG_IV_CIPHERTEXT_HEX: &str = "140833b120e1faecb3ff52ba58aa683f18a9ba042a2b94fb4ec690c365d9effc64647f793d117b620d5d08125e70ca19";

/// AES-256-CBC, OPENSSL_ZERO_PADDING, two-block plaintext.
pub const ZERO_PAD_CBC_CIPHERTEXT_HEX: &str = "471e64cc510482e98305e3091b78fdbd91dbec72fc540174e38d251b11e15285";

/// AES-256-ECB, OPENSSL_ZERO_PADDING, two-block plaintext.
pub const ZERO_PAD_ECB_CIPHERTEXT_HEX: &str = "445e32f8fd230ab9e848ad2e34a610bc445e32f8fd230ab9e848ad2e34a610bc";

/// AES-256-CBC default mode (no OPENSSL_RAW_DATA): base64 of the ciphertext.
pub const CBC_BASE64: &str = "vjHwei9me/NHVOjsRbsmgr8x9DDcswOrCJp60TzpOCYLVV1y+KcUFF5Dr3y1CiHh";

/// AES-256-CBC ciphertext for the name "AES-256-CBC" — must equal the
/// lowercase-name vector, pinning case-insensitive cipher lookup.
pub const UPPERCASE_NAME_CIPHERTEXT_HEX: &str = "be31f07a2f667bf34754e8ec45bb2682bf31f430dcb303ab089a7ad13ce938260b555d72f8a714145e43af7cb50a21e1";
