//! Purpose:
//! Statement builders for the synthetic DatePeriod method bodies.
//!
//! Called from:
//! - The sibling module's method assembly.
//!
//! Key details:
//! - BUILT, not parsed. Each function reproduces the AST its `*_SRC` PHP constant parses to;
//!   the oracle test in the parent module compares them node by node, which is what makes
//!   these hand-reviewable transcriptions safe to rely on.
//! - Generated by `synthetic_class::transcribe`, then reviewed.

use crate::parser::ast::{BinOp, CastType, Stmt};
use crate::synthetic_class::{
    e_binop,
    e_bool,
    e_call,
    e_cast,
    e_index,
    e_int,
    e_method_call,
    e_new,
    e_null,
    e_str,
    e_ternary,
    e_this_prop,
    e_var,
    s_assign,
    s_break,
    s_expr,
    s_if,
    s_return,
    s_throw,
    s_try,
    s_while,
};

/// Reproduces `CREATE_FROM_ISO8601_SRC`.
pub(super) fn create_from_iso8601() -> Vec<Stmt> {
    vec![
        s_assign("bad", e_binop(e_binop(e_str("Unknown or bad format ("), BinOp::Concat, e_var("specification")), BinOp::Concat, e_str(")"))),
        s_assign("badRecur", e_str("DatePeriod::createFromISO8601String(): Recurrence count must be greater or equal to 1 and lower than 2147483640")),
        s_assign("len", e_call("strlen", vec![e_var("specification")])),
        s_if(
            e_binop(e_var("len"), BinOp::Lt, e_int(3)),
            vec![
                s_throw(e_new("DateMalformedPeriodStringException", vec![e_var("bad")])),
            ],
            vec![],
            None,
        ),
        s_assign("recurrences", e_int(0)),
        s_if(
            e_binop(e_index(e_var("specification"), e_int(0)), BinOp::StrictEq, e_str("R")),
            vec![
                s_assign("slash", e_call("strpos", vec![e_var("specification"), e_str("/")])),
                s_if(
                    e_binop(e_binop(e_var("slash"), BinOp::StrictEq, e_bool(false)), BinOp::Or, e_binop(e_var("slash"), BinOp::Lt, e_int(2))),
                    vec![
                        s_throw(e_new("DateMalformedPeriodStringException", vec![e_var("bad")])),
                    ],
                    vec![],
                    None,
                ),
                s_assign("prefix", e_call("substr", vec![e_var("specification"), e_int(1), e_binop(e_var("slash"), BinOp::Sub, e_int(1))])),
                s_if(
                    e_binop(e_var("prefix"), BinOp::StrictEq, e_str("")),
                    vec![
                        s_throw(e_new("DateMalformedPeriodStringException", vec![e_var("bad")])),
                    ],
                    vec![],
                    None,
                ),
                s_if(
                    e_binop(e_index(e_var("prefix"), e_int(0)), BinOp::StrictEq, e_str("0")),
                    vec![
                        s_throw(e_new("DateMalformedPeriodStringException", vec![e_var("badRecur")])),
                    ],
                    vec![],
                    None,
                ),
                s_assign("digits", e_str("0123456789")),
                s_assign("all_digits", e_int(1)),
                s_assign("pi", e_int(0)),
                s_while(e_binop(e_var("pi"), BinOp::Lt, e_call("strlen", vec![e_var("prefix")])), vec![
                    s_assign("ch", e_index(e_var("prefix"), e_var("pi"))),
                    s_assign("found", e_int(0)),
                    s_assign("di", e_int(0)),
                    s_while(e_binop(e_var("di"), BinOp::Lt, e_int(10)), vec![
                        s_if(
                            e_binop(e_index(e_var("digits"), e_var("di")), BinOp::StrictEq, e_var("ch")),
                            vec![
                                s_assign("found", e_int(1)),
                                s_break(1),
                            ],
                            vec![],
                            None,
                        ),
                        s_assign("di", e_binop(e_var("di"), BinOp::Add, e_int(1))),
                    ]),
                    s_if(
                        e_binop(e_var("found"), BinOp::StrictEq, e_int(0)),
                        vec![
                            s_assign("all_digits", e_int(0)),
                            s_break(1),
                        ],
                        vec![],
                        None,
                    ),
                    s_assign("pi", e_binop(e_var("pi"), BinOp::Add, e_int(1))),
                ]),
                s_if(
                    e_binop(e_var("all_digits"), BinOp::StrictEq, e_int(0)),
                    vec![
                        s_throw(e_new("DateMalformedPeriodStringException", vec![e_var("bad")])),
                    ],
                    vec![],
                    None,
                ),
                s_assign("recurrences", e_cast(CastType::Int, e_var("prefix"))),
                s_if(
                    e_binop(e_var("recurrences"), BinOp::Lt, e_int(1)),
                    vec![
                        s_throw(e_new("DateMalformedPeriodStringException", vec![e_var("badRecur")])),
                    ],
                    vec![],
                    None,
                ),
                s_assign("rest", e_call("substr", vec![e_var("specification"), e_binop(e_var("slash"), BinOp::Add, e_int(1))])),
            ],
            vec![],
            Some(vec![
            s_assign("rest", e_var("specification")),
        ]),
        ),
        s_assign("parts", e_call("explode", vec![e_str("/"), e_var("rest")])),
        s_assign("nparts", e_call("count", vec![e_var("parts")])),
        s_assign("start_str", e_index(e_var("parts"), e_int(0))),
        s_assign("interval_str", e_ternary(e_binop(e_var("nparts"), BinOp::GtEq, e_int(2)), e_index(e_var("parts"), e_int(1)), e_str("P1D"))),
        s_assign("end_str", e_ternary(e_binop(e_var("nparts"), BinOp::GtEq, e_int(3)), e_index(e_var("parts"), e_int(2)), e_str(""))),
        s_if(
            e_binop(e_binop(e_var("start_str"), BinOp::StrictEq, e_str("")), BinOp::Or, e_binop(e_var("interval_str"), BinOp::StrictEq, e_str(""))),
            vec![
                s_throw(e_new("DateMalformedPeriodStringException", vec![e_var("bad")])),
            ],
            vec![],
            None,
        ),
        s_assign("has_end", e_ternary(e_binop(e_var("end_str"), BinOp::StrictNotEq, e_str("")), e_int(1), e_int(0))),
        s_if(
            e_binop(e_binop(e_var("has_end"), BinOp::StrictEq, e_int(0)), BinOp::And, e_binop(e_var("recurrences"), BinOp::Lt, e_int(1))),
            vec![
                s_throw(e_new("DateMalformedPeriodStringException", vec![e_var("bad")])),
            ],
            vec![],
            None,
        ),
        s_try(vec![
            s_assign("start_dt", e_new("DateTime", vec![e_var("start_str")])),
            s_assign("iv", e_new("DateInterval", vec![e_var("interval_str")])),
        ], vec![
            (vec!["Exception"], Some("e"), vec![
                s_throw(e_new("DateMalformedPeriodStringException", vec![e_var("bad")])),
            ]),
        ], None),
        s_if(
            e_binop(e_var("has_end"), BinOp::StrictEq, e_int(1)),
            vec![
                s_try(vec![
                    s_assign("end_dt", e_new("DateTime", vec![e_var("end_str")])),
                ], vec![
                    (vec!["Exception"], Some("e"), vec![
                        s_throw(e_new("DateMalformedPeriodStringException", vec![e_var("bad")])),
                    ]),
                ], None),
                s_return(e_new("DatePeriod", vec![e_var("start_dt"), e_var("iv"), e_var("end_dt"), e_var("options")])),
            ],
            vec![],
            None,
        ),
        s_return(e_new("DatePeriod", vec![e_var("start_dt"), e_var("iv"), e_var("recurrences"), e_var("options")])),
    ]
}

/// Reproduces `CURRENT_SRC`.
pub(super) fn current() -> Vec<Stmt> {
    vec![
        s_if(
            e_this_prop("startIsImmutable"),
            vec![
                s_assign("d", e_new("DateTimeImmutable", vec![])),
                s_return(e_method_call(e_var("d"), "setTimestamp", vec![e_this_prop("curTs")])),
            ],
            vec![],
            None,
        ),
        s_assign("d", e_new("DateTime", vec![])),
        s_expr(e_method_call(e_var("d"), "setTimestamp", vec![e_this_prop("curTs")])),
        s_return(e_var("d")),
    ]
}

/// Reproduces `GET_END_DATE_SRC`.
pub(super) fn get_end_date() -> Vec<Stmt> {
    vec![
        s_if(
            e_this_prop("useCount"),
            vec![
                s_return(e_null()),
            ],
            vec![],
            None,
        ),
        s_assign("d", e_new("DateTime", vec![])),
        s_expr(e_method_call(e_var("d"), "setTimestamp", vec![e_this_prop("endTs")])),
        s_return(e_var("d")),
    ]
}

/// Reproduces `GET_START_DATE_SRC`.
pub(super) fn get_start_date() -> Vec<Stmt> {
    vec![
        s_if(
            e_this_prop("startIsImmutable"),
            vec![
                s_assign("d", e_new("DateTimeImmutable", vec![])),
                s_return(e_method_call(e_var("d"), "setTimestamp", vec![e_this_prop("startTs")])),
            ],
            vec![],
            None,
        ),
        s_assign("d", e_new("DateTime", vec![])),
        s_expr(e_method_call(e_var("d"), "setTimestamp", vec![e_this_prop("startTs")])),
        s_return(e_var("d")),
    ]
}
