//! Purpose:
//! Writes the Node.js ESM package produced by `--emit npm` for a compiled
//! wasm32-wasi command module.
//!
//! Called from:
//! - `crate::pipeline::emit_wasm_artifacts()` after WAT has been encoded to WASM.
//!
//! Key details:
//! - The generated loader uses Node's built-in `node:wasi` preview1 runtime.
//! - The package keeps the WASM binary beside the loader and exposes a reusable
//!   asynchronous `run()` API as well as a directly executable `index.mjs`.

use serde_json::json;
use std::fs;
use std::io;
use std::path::Path;

const WASM_FILENAME: &str = "module.wasm";

/// Writes a complete Node.js ESM package containing `wasm_bytes`.
pub fn write_package(
    package_dir: &Path,
    source_stem: &str,
    wasm_bytes: &[u8],
) -> io::Result<()> {
    fs::create_dir_all(package_dir)?;
    let package_name = npm_package_name(source_stem);
    let package_json = serde_json::to_string_pretty(&json!({
        "name": &package_name,
        "version": "0.0.0",
        "description": format!("wasm32-wasi command compiled from {source_stem}.php by elephc"),
        "type": "module",
        "exports": "./index.mjs",
        "types": "./index.d.ts",
        "files": [
            "index.mjs",
            "index.d.ts",
            WASM_FILENAME,
            "README.md"
        ],
        "engines": {
            "node": ">=20.0.0"
        }
    }))
    .map_err(io::Error::other)?;

    fs::write(package_dir.join(WASM_FILENAME), wasm_bytes)?;
    fs::write(package_dir.join("package.json"), format!("{package_json}\n"))?;
    fs::write(package_dir.join("index.mjs"), loader_source(&package_name))?;
    fs::write(package_dir.join("index.d.ts"), type_declarations())?;
    fs::write(
        package_dir.join("README.md"),
        readme_source(&package_name, source_stem),
    )?;
    Ok(())
}

/// Converts a source stem into a valid, deterministic unscoped NPM package name.
fn npm_package_name(source_stem: &str) -> String {
    let mut name = String::with_capacity(source_stem.len());
    let mut previous_dash = false;
    for ch in source_stem.chars() {
        let normalized = if ch.is_ascii_alphanumeric() {
            Some(ch.to_ascii_lowercase())
        } else if matches!(ch, '-' | '_' | '.') {
            Some(ch)
        } else {
            Some('-')
        };
        if let Some(ch) = normalized {
            if ch == '-' {
                if previous_dash {
                    continue;
                }
                previous_dash = true;
            } else {
                previous_dash = false;
            }
            name.push(ch);
        }
    }
    let name = name.trim_matches(['-', '.', '_']);
    if name.is_empty() {
        "elephc-wasm".to_string()
    } else {
        name.to_string()
    }
}

/// Renders the reusable and directly executable Node.js WASI loader.
fn loader_source(package_name: &str) -> String {
    format!(
        r#"import {{ realpathSync }} from "node:fs";
import {{ readFile }} from "node:fs/promises";
import {{ fileURLToPath }} from "node:url";
import {{ WASI }} from "node:wasi";

const wasmUrl = new URL("./{WASM_FILENAME}", import.meta.url);

/**
 * Runs the compiled PHP command under Node's WASI preview1 runtime.
 *
 * @param {{ args?: string[], env?: Record<string, string>, preopens?: Record<string, string> }} options
 * @returns {{Promise<number>}} the WASI process exit code
 */
export async function run({{
  args = ["{package_name}"],
  env = process.env,
  preopens = {{}},
}} = {{}}) {{
  const wasi = new WASI({{
    version: "preview1",
    args,
    env,
    preopens,
    returnOnExit: true,
  }});
  const module = await WebAssembly.compile(await readFile(wasmUrl));
  const instance = await WebAssembly.instantiate(module, wasi.getImportObject());
  const exitCode = wasi.start(instance);
  return typeof exitCode === "number" ? exitCode : 0;
}}

const invokedPath = process.argv[1];
if (
  invokedPath &&
  realpathSync(invokedPath) === realpathSync(fileURLToPath(import.meta.url))
) {{
  process.exitCode = await run({{
    args: [invokedPath, ...process.argv.slice(2)],
  }});
}}
"#
    )
}

/// Returns TypeScript declarations for the generated loader API.
fn type_declarations() -> &'static str {
    r#"export interface RunOptions {
  args?: string[];
  env?: Record<string, string>;
  preopens?: Record<string, string>;
}

export declare function run(options?: RunOptions): Promise<number>;
"#
}

/// Renders concise usage documentation for the generated package.
fn readme_source(package_name: &str, source_stem: &str) -> String {
    format!(
        r#"# {package_name}

Node.js WASI package generated by elephc from `{source_stem}.php`.

Requires Node.js 20 or newer.

```js
import {{ run }} from "{package_name}";

const exitCode = await run({{
  args: ["{package_name}", "first-argument"],
  env: process.env,
  preopens: {{ "/work": process.cwd() }},
}});
```

Run the command directly:

```bash
node index.mjs first-argument
```
"#
    )
}

#[cfg(test)]
mod tests {
    //! Purpose:
    //! Regression tests for the generated Node.js WASI package layout and metadata.
    //!
    //! Called from:
    //! - `cargo test` through Rust's test harness.
    //!
    //! Key details:
    //! - Tests use a unique temporary directory and do not require Node.js.

    use super::{npm_package_name, write_package};
    use std::fs;
    use std::sync::atomic::{AtomicU32, Ordering};

    static TMP_SEQ: AtomicU32 = AtomicU32::new(0);

    /// Returns a unique temporary package directory for a parallel test run.
    fn temp_package_dir() -> std::path::PathBuf {
        let sequence = TMP_SEQ.fetch_add(1, Ordering::Relaxed);
        std::env::temp_dir().join(format!(
            "elephc_npm_package_{}_{}",
            std::process::id(),
            sequence
        ))
    }

    /// Verifies package names are lowercase, NPM-safe, and never empty.
    #[test]
    fn normalizes_npm_package_names() {
        assert_eq!(npm_package_name("Hello_WASM"), "hello_wasm");
        assert_eq!(npm_package_name("hello world!"), "hello-world");
        assert_eq!(npm_package_name("..."), "elephc-wasm");
    }

    /// Verifies `--emit npm` writes the binary, ESM loader, types, metadata, and README.
    #[test]
    fn writes_complete_npm_package() {
        let package_dir = temp_package_dir();
        let wasm = b"\0asm\x01\0\0\0";
        write_package(&package_dir, "Hello App", wasm).expect("write npm package");

        assert_eq!(
            fs::read(package_dir.join("module.wasm")).expect("read module"),
            wasm
        );
        let metadata: serde_json::Value = serde_json::from_slice(
            &fs::read(package_dir.join("package.json")).expect("read package metadata"),
        )
        .expect("parse package metadata");
        assert_eq!(metadata["name"], "hello-app");
        assert_eq!(metadata["type"], "module");
        assert_eq!(metadata["exports"], "./index.mjs");

        let loader = fs::read_to_string(package_dir.join("index.mjs")).expect("read loader");
        assert!(loader.contains("new WASI"));
        assert!(loader.contains("version: \"preview1\""));
        assert!(loader.contains("wasi.getImportObject()"));
        assert!(loader.contains("export async function run"));
        assert!(package_dir.join("index.d.ts").is_file());
        assert!(package_dir.join("README.md").is_file());

        fs::remove_dir_all(package_dir).expect("remove temporary package");
    }
}
