//! Purpose:
//! Statement builders for the synthetic ext/calendar helper method bodies.
//!
//! Called from:
//! - The sibling module's method assembly.
//!
//! Key details:
//! - BUILT, not parsed. Each function reproduces the AST its `*_SRC` PHP constant parses to;
//!   the oracle test in the parent module compares them node by node, which is what makes
//!   these hand-reviewable transcriptions safe to rely on.
//! - Generated by `synthetic_class::transcribe`, then reviewed.

use crate::parser::ast::{BinOp, Stmt};
use crate::synthetic_class::{
    e_array,
    e_array_assoc,
    e_binop,
    e_call,
    e_index,
    e_int,
    e_neg,
    e_not,
    e_static_call,
    e_str,
    e_ternary,
    e_var,
    s_assign,
    s_break,
    s_if,
    s_return,
    s_while,
};

/// Reproduces `CAL_DAYS_IN_MONTH_SRC`.
pub(super) fn cal_days_in_month() -> Vec<Stmt> {
    vec![
        s_assign("start", e_static_call("DateTime", "__elephc_cal_to_jd", vec![e_var("calendar"), e_var("month"), e_int(1), e_var("year")])),
        s_assign("next", e_static_call("DateTime", "__elephc_cal_to_jd", vec![e_var("calendar"), e_binop(e_var("month"), BinOp::Add, e_int(1)), e_int(1), e_var("year")])),
        s_if(
            e_binop(e_var("next"), BinOp::Eq, e_int(0)),
            vec![
                s_if(
                    e_binop(e_var("year"), BinOp::Eq, e_neg(e_int(1))),
                    vec![
                        s_assign("next", e_static_call("DateTime", "__elephc_cal_to_jd", vec![e_var("calendar"), e_int(1), e_int(1), e_int(1)])),
                    ],
                    vec![],
                    Some(vec![
                    s_assign("next", e_static_call("DateTime", "__elephc_cal_to_jd", vec![e_var("calendar"), e_int(1), e_int(1), e_binop(e_var("year"), BinOp::Add, e_int(1))])),
                    s_if(
                        e_binop(e_binop(e_var("calendar"), BinOp::Eq, e_int(3)), BinOp::And, e_binop(e_var("next"), BinOp::Eq, e_int(0))),
                        vec![
                            s_assign("next", e_int(2380953)),
                        ],
                        vec![],
                        None,
                    ),
                ]),
                ),
            ],
            vec![],
            None,
        ),
        s_return(e_binop(e_var("next"), BinOp::Sub, e_var("start"))),
    ]
}

/// Reproduces `CAL_FROM_JD_SRC`.
pub(super) fn cal_from_jd() -> Vec<Stmt> {
    vec![
        s_assign("gregShort", e_array(vec![e_str(""), e_str("Jan"), e_str("Feb"), e_str("Mar"), e_str("Apr"), e_str("May"), e_str("Jun"), e_str("Jul"), e_str("Aug"), e_str("Sep"), e_str("Oct"), e_str("Nov"), e_str("Dec")])),
        s_assign("gregLong", e_array(vec![e_str(""), e_str("January"), e_str("February"), e_str("March"), e_str("April"), e_str("May"), e_str("June"), e_str("July"), e_str("August"), e_str("September"), e_str("October"), e_str("November"), e_str("December")])),
        s_assign("french", e_array(vec![e_str(""), e_str("Vendemiaire"), e_str("Brumaire"), e_str("Frimaire"), e_str("Nivose"), e_str("Pluviose"), e_str("Ventose"), e_str("Germinal"), e_str("Floreal"), e_str("Prairial"), e_str("Messidor"), e_str("Thermidor"), e_str("Fructidor"), e_str("Extra")])),
        s_assign("dayLong", e_array(vec![e_str("Sunday"), e_str("Monday"), e_str("Tuesday"), e_str("Wednesday"), e_str("Thursday"), e_str("Friday"), e_str("Saturday")])),
        s_assign("dayShort", e_array(vec![e_str("Sun"), e_str("Mon"), e_str("Tue"), e_str("Wed"), e_str("Thu"), e_str("Fri"), e_str("Sat")])),
        s_if(
            e_binop(e_var("calendar"), BinOp::Eq, e_int(1)),
            vec![
                s_assign("r", e_static_call("DateTime", "__elephc_sdn_to_jul", vec![e_var("jd")])),
            ],
            vec![],
            Some(vec![
            s_if(
                e_binop(e_var("calendar"), BinOp::Eq, e_int(2)),
                vec![
                    s_assign("r", e_static_call("DateTime", "__elephc_sdn_to_jew", vec![e_var("jd")])),
                ],
                vec![],
                Some(vec![
                s_if(
                    e_binop(e_var("calendar"), BinOp::Eq, e_int(3)),
                    vec![
                        s_assign("r", e_static_call("DateTime", "__elephc_sdn_to_fr", vec![e_var("jd")])),
                    ],
                    vec![],
                    Some(vec![
                    s_assign("r", e_static_call("DateTime", "__elephc_sdn_to_greg", vec![e_var("jd")])),
                ]),
                ),
            ]),
            ),
        ]),
        ),
        s_assign("y", e_index(e_var("r"), e_str("y"))),
        s_assign("m", e_index(e_var("r"), e_str("m"))),
        s_assign("d", e_index(e_var("r"), e_str("d"))),
        s_assign("dow", e_binop(e_binop(e_binop(e_var("jd"), BinOp::Mod, e_int(7)), BinOp::Add, e_int(8)), BinOp::Mod, e_int(7))),
        s_if(
            e_binop(e_binop(e_var("calendar"), BinOp::Eq, e_int(2)), BinOp::And, e_binop(e_var("y"), BinOp::LtEq, e_int(0))),
            vec![
                s_assign("abMonth", e_str("")),
                s_assign("monthName", e_str("")),
            ],
            vec![],
            Some(vec![
            s_if(
                e_binop(e_var("calendar"), BinOp::Eq, e_int(2)),
                vec![
                    s_assign("abMonth", e_static_call("DateTime", "__elephc_jew_month_name", vec![e_var("y"), e_var("m")])),
                    s_assign("monthName", e_var("abMonth")),
                ],
                vec![],
                Some(vec![
                s_if(
                    e_binop(e_var("calendar"), BinOp::Eq, e_int(1)),
                    vec![
                        s_assign("abMonth", e_index(e_var("gregShort"), e_var("m"))),
                        s_assign("monthName", e_index(e_var("gregLong"), e_var("m"))),
                    ],
                    vec![],
                    Some(vec![
                    s_if(
                        e_binop(e_var("calendar"), BinOp::Eq, e_int(3)),
                        vec![
                            s_assign("abMonth", e_index(e_var("french"), e_var("m"))),
                            s_assign("monthName", e_index(e_var("french"), e_var("m"))),
                        ],
                        vec![],
                        Some(vec![
                        s_assign("abMonth", e_index(e_var("gregShort"), e_var("m"))),
                        s_assign("monthName", e_index(e_var("gregLong"), e_var("m"))),
                    ]),
                    ),
                ]),
                ),
            ]),
            ),
        ]),
        ),
        s_return(e_array_assoc(vec![(e_str("date"), e_binop(e_binop(e_binop(e_binop(e_var("m"), BinOp::Concat, e_str("/")), BinOp::Concat, e_var("d")), BinOp::Concat, e_str("/")), BinOp::Concat, e_var("y"))), (e_str("month"), e_var("m")), (e_str("day"), e_var("d")), (e_str("year"), e_var("y")), (e_str("dow"), e_var("dow")), (e_str("abbrevdayname"), e_index(e_var("dayShort"), e_var("dow"))), (e_str("dayname"), e_index(e_var("dayLong"), e_var("dow"))), (e_str("abbrevmonth"), e_var("abMonth")), (e_str("monthname"), e_var("monthName"))])),
    ]
}

/// Reproduces `CAL_INFO_SRC`.
pub(super) fn cal_info() -> Vec<Stmt> {
    vec![
        s_assign("greg", e_array_assoc(vec![(e_str("months"), e_array_assoc(vec![(e_int(1), e_str("January")), (e_int(2), e_str("February")), (e_int(3), e_str("March")), (e_int(4), e_str("April")), (e_int(5), e_str("May")), (e_int(6), e_str("June")), (e_int(7), e_str("July")), (e_int(8), e_str("August")), (e_int(9), e_str("September")), (e_int(10), e_str("October")), (e_int(11), e_str("November")), (e_int(12), e_str("December"))])), (e_str("abbrevmonths"), e_array_assoc(vec![(e_int(1), e_str("Jan")), (e_int(2), e_str("Feb")), (e_int(3), e_str("Mar")), (e_int(4), e_str("Apr")), (e_int(5), e_str("May")), (e_int(6), e_str("Jun")), (e_int(7), e_str("Jul")), (e_int(8), e_str("Aug")), (e_int(9), e_str("Sep")), (e_int(10), e_str("Oct")), (e_int(11), e_str("Nov")), (e_int(12), e_str("Dec"))])), (e_str("maxdaysinmonth"), e_int(31)), (e_str("calname"), e_str("Gregorian")), (e_str("calsymbol"), e_str("CAL_GREGORIAN"))])),
        s_assign("jul", e_array_assoc(vec![(e_str("months"), e_array_assoc(vec![(e_int(1), e_str("January")), (e_int(2), e_str("February")), (e_int(3), e_str("March")), (e_int(4), e_str("April")), (e_int(5), e_str("May")), (e_int(6), e_str("June")), (e_int(7), e_str("July")), (e_int(8), e_str("August")), (e_int(9), e_str("September")), (e_int(10), e_str("October")), (e_int(11), e_str("November")), (e_int(12), e_str("December"))])), (e_str("abbrevmonths"), e_array_assoc(vec![(e_int(1), e_str("Jan")), (e_int(2), e_str("Feb")), (e_int(3), e_str("Mar")), (e_int(4), e_str("Apr")), (e_int(5), e_str("May")), (e_int(6), e_str("Jun")), (e_int(7), e_str("Jul")), (e_int(8), e_str("Aug")), (e_int(9), e_str("Sep")), (e_int(10), e_str("Oct")), (e_int(11), e_str("Nov")), (e_int(12), e_str("Dec"))])), (e_str("maxdaysinmonth"), e_int(31)), (e_str("calname"), e_str("Julian")), (e_str("calsymbol"), e_str("CAL_JULIAN"))])),
        s_assign("jew", e_array_assoc(vec![(e_str("months"), e_array_assoc(vec![(e_int(1), e_str("Tishri")), (e_int(2), e_str("Heshvan")), (e_int(3), e_str("Kislev")), (e_int(4), e_str("Tevet")), (e_int(5), e_str("Shevat")), (e_int(6), e_str("Adar I")), (e_int(7), e_str("Adar II")), (e_int(8), e_str("Nisan")), (e_int(9), e_str("Iyyar")), (e_int(10), e_str("Sivan")), (e_int(11), e_str("Tammuz")), (e_int(12), e_str("Av")), (e_int(13), e_str("Elul"))])), (e_str("abbrevmonths"), e_array_assoc(vec![(e_int(1), e_str("Tishri")), (e_int(2), e_str("Heshvan")), (e_int(3), e_str("Kislev")), (e_int(4), e_str("Tevet")), (e_int(5), e_str("Shevat")), (e_int(6), e_str("Adar I")), (e_int(7), e_str("Adar II")), (e_int(8), e_str("Nisan")), (e_int(9), e_str("Iyyar")), (e_int(10), e_str("Sivan")), (e_int(11), e_str("Tammuz")), (e_int(12), e_str("Av")), (e_int(13), e_str("Elul"))])), (e_str("maxdaysinmonth"), e_int(30)), (e_str("calname"), e_str("Jewish")), (e_str("calsymbol"), e_str("CAL_JEWISH"))])),
        s_assign("fr", e_array_assoc(vec![(e_str("months"), e_array_assoc(vec![(e_int(1), e_str("Vendemiaire")), (e_int(2), e_str("Brumaire")), (e_int(3), e_str("Frimaire")), (e_int(4), e_str("Nivose")), (e_int(5), e_str("Pluviose")), (e_int(6), e_str("Ventose")), (e_int(7), e_str("Germinal")), (e_int(8), e_str("Floreal")), (e_int(9), e_str("Prairial")), (e_int(10), e_str("Messidor")), (e_int(11), e_str("Thermidor")), (e_int(12), e_str("Fructidor")), (e_int(13), e_str("Extra"))])), (e_str("abbrevmonths"), e_array_assoc(vec![(e_int(1), e_str("Vendemiaire")), (e_int(2), e_str("Brumaire")), (e_int(3), e_str("Frimaire")), (e_int(4), e_str("Nivose")), (e_int(5), e_str("Pluviose")), (e_int(6), e_str("Ventose")), (e_int(7), e_str("Germinal")), (e_int(8), e_str("Floreal")), (e_int(9), e_str("Prairial")), (e_int(10), e_str("Messidor")), (e_int(11), e_str("Thermidor")), (e_int(12), e_str("Fructidor")), (e_int(13), e_str("Extra"))])), (e_str("maxdaysinmonth"), e_int(30)), (e_str("calname"), e_str("French")), (e_str("calsymbol"), e_str("CAL_FRENCH"))])),
        s_if(
            e_binop(e_var("calendar"), BinOp::Eq, e_int(0)),
            vec![
                s_return(e_var("greg")),
            ],
            vec![],
            None,
        ),
        s_if(
            e_binop(e_var("calendar"), BinOp::Eq, e_int(1)),
            vec![
                s_return(e_var("jul")),
            ],
            vec![],
            None,
        ),
        s_if(
            e_binop(e_var("calendar"), BinOp::Eq, e_int(2)),
            vec![
                s_return(e_var("jew")),
            ],
            vec![],
            None,
        ),
        s_if(
            e_binop(e_var("calendar"), BinOp::Eq, e_int(3)),
            vec![
                s_return(e_var("fr")),
            ],
            vec![],
            None,
        ),
        s_return(e_array_assoc(vec![(e_int(0), e_var("greg")), (e_int(1), e_var("jul")), (e_int(2), e_var("jew")), (e_int(3), e_var("fr"))])),
    ]
}

/// Reproduces `CAL_TO_JD_SRC`.
pub(super) fn cal_to_jd() -> Vec<Stmt> {
    vec![
        s_if(
            e_binop(e_var("calendar"), BinOp::Eq, e_int(0)),
            vec![
                s_return(e_static_call("DateTime", "__elephc_greg_to_sdn", vec![e_var("year"), e_var("month"), e_var("day")])),
            ],
            vec![],
            None,
        ),
        s_if(
            e_binop(e_var("calendar"), BinOp::Eq, e_int(1)),
            vec![
                s_return(e_static_call("DateTime", "__elephc_jul_to_sdn", vec![e_var("year"), e_var("month"), e_var("day")])),
            ],
            vec![],
            None,
        ),
        s_if(
            e_binop(e_var("calendar"), BinOp::Eq, e_int(2)),
            vec![
                s_return(e_static_call("DateTime", "__elephc_jew_to_sdn", vec![e_var("year"), e_var("month"), e_var("day")])),
            ],
            vec![],
            None,
        ),
        s_if(
            e_binop(e_var("calendar"), BinOp::Eq, e_int(3)),
            vec![
                s_return(e_static_call("DateTime", "__elephc_fr_to_sdn", vec![e_var("year"), e_var("month"), e_var("day")])),
            ],
            vec![],
            None,
        ),
        s_return(e_int(0)),
    ]
}

/// Reproduces `EASTER_CALC_SRC`.
pub(super) fn easter_calc() -> Vec<Stmt> {
    vec![
        s_assign("golden", e_binop(e_binop(e_var("year"), BinOp::Mod, e_int(19)), BinOp::Add, e_int(1))),
        s_if(
            e_binop(e_binop(e_binop(e_binop(e_var("year"), BinOp::LtEq, e_int(1582)), BinOp::And, e_binop(e_var("method"), BinOp::NotEq, e_int(2))), BinOp::Or, e_binop(e_binop(e_binop(e_binop(e_var("year"), BinOp::GtEq, e_int(1583)), BinOp::And, e_binop(e_var("year"), BinOp::LtEq, e_int(1752))), BinOp::And, e_binop(e_var("method"), BinOp::NotEq, e_int(1))), BinOp::And, e_binop(e_var("method"), BinOp::NotEq, e_int(2)))), BinOp::Or, e_binop(e_var("method"), BinOp::Eq, e_int(3))),
            vec![
                s_assign("dom", e_binop(e_binop(e_binop(e_var("year"), BinOp::Add, e_call("intdiv", vec![e_var("year"), e_int(4)])), BinOp::Add, e_int(5)), BinOp::Mod, e_int(7))),
                s_if(
                    e_binop(e_var("dom"), BinOp::Lt, e_int(0)),
                    vec![
                        s_assign("dom", e_binop(e_var("dom"), BinOp::Add, e_int(7))),
                    ],
                    vec![],
                    None,
                ),
                s_assign("pfm", e_binop(e_binop(e_binop(e_int(3), BinOp::Sub, e_binop(e_int(11), BinOp::Mul, e_var("golden"))), BinOp::Sub, e_int(7)), BinOp::Mod, e_int(30))),
                s_if(
                    e_binop(e_var("pfm"), BinOp::Lt, e_int(0)),
                    vec![
                        s_assign("pfm", e_binop(e_var("pfm"), BinOp::Add, e_int(30))),
                    ],
                    vec![],
                    None,
                ),
            ],
            vec![],
            Some(vec![
            s_assign("dom", e_binop(e_binop(e_binop(e_binop(e_var("year"), BinOp::Add, e_call("intdiv", vec![e_var("year"), e_int(4)])), BinOp::Sub, e_call("intdiv", vec![e_var("year"), e_int(100)])), BinOp::Add, e_call("intdiv", vec![e_var("year"), e_int(400)])), BinOp::Mod, e_int(7))),
            s_if(
                e_binop(e_var("dom"), BinOp::Lt, e_int(0)),
                vec![
                    s_assign("dom", e_binop(e_var("dom"), BinOp::Add, e_int(7))),
                ],
                vec![],
                None,
            ),
            s_assign("solar", e_binop(e_call("intdiv", vec![e_binop(e_var("year"), BinOp::Sub, e_int(1600)), e_int(100)]), BinOp::Sub, e_call("intdiv", vec![e_binop(e_var("year"), BinOp::Sub, e_int(1600)), e_int(400)]))),
            s_assign("lunar", e_call("intdiv", vec![e_binop(e_call("intdiv", vec![e_binop(e_var("year"), BinOp::Sub, e_int(1400)), e_int(100)]), BinOp::Mul, e_int(8)), e_int(25)])),
            s_assign("pfm", e_binop(e_binop(e_binop(e_binop(e_int(3), BinOp::Sub, e_binop(e_int(11), BinOp::Mul, e_var("golden"))), BinOp::Add, e_var("solar")), BinOp::Sub, e_var("lunar")), BinOp::Mod, e_int(30))),
            s_if(
                e_binop(e_var("pfm"), BinOp::Lt, e_int(0)),
                vec![
                    s_assign("pfm", e_binop(e_var("pfm"), BinOp::Add, e_int(30))),
                ],
                vec![],
                None,
            ),
        ]),
        ),
        s_if(
            e_binop(e_binop(e_var("pfm"), BinOp::Eq, e_int(29)), BinOp::Or, e_binop(e_binop(e_var("pfm"), BinOp::Eq, e_int(28)), BinOp::And, e_binop(e_var("golden"), BinOp::Gt, e_int(11)))),
            vec![
                s_assign("pfm", e_binop(e_var("pfm"), BinOp::Sub, e_int(1))),
            ],
            vec![],
            None,
        ),
        s_assign("tmp", e_binop(e_binop(e_binop(e_int(4), BinOp::Sub, e_var("pfm")), BinOp::Sub, e_var("dom")), BinOp::Mod, e_int(7))),
        s_if(
            e_binop(e_var("tmp"), BinOp::Lt, e_int(0)),
            vec![
                s_assign("tmp", e_binop(e_var("tmp"), BinOp::Add, e_int(7))),
            ],
            vec![],
            None,
        ),
        s_assign("easter", e_binop(e_binop(e_var("pfm"), BinOp::Add, e_var("tmp")), BinOp::Add, e_int(1))),
        s_if(
            e_binop(e_var("gm"), BinOp::NotEq, e_int(0)),
            vec![
                s_if(
                    e_binop(e_var("easter"), BinOp::Lt, e_int(11)),
                    vec![
                        s_assign("mon", e_int(3)),
                        s_assign("mday", e_binop(e_var("easter"), BinOp::Add, e_int(21))),
                    ],
                    vec![],
                    Some(vec![
                    s_assign("mon", e_int(4)),
                    s_assign("mday", e_binop(e_var("easter"), BinOp::Sub, e_int(10))),
                ]),
                ),
                s_return(e_call("__elephc_mktime_raw", vec![e_int(0), e_int(0), e_int(0), e_var("mon"), e_var("mday"), e_var("year")])),
            ],
            vec![],
            None,
        ),
        s_return(e_var("easter")),
    ]
}

/// Reproduces `EASTER_DATE_SRC`.
pub(super) fn easter_date() -> Vec<Stmt> {
    vec![
        s_return(e_static_call("DateTime", "__elephc_easter_calc", vec![e_var("year"), e_var("mode"), e_int(1)])),
    ]
}

/// Reproduces `EASTER_DAYS_SRC`.
pub(super) fn easter_days() -> Vec<Stmt> {
    vec![
        s_return(e_static_call("DateTime", "__elephc_easter_calc", vec![e_var("year"), e_var("mode"), e_int(0)])),
    ]
}

/// Reproduces `FRENCHTOJD_SRC`.
pub(super) fn frenchtojd() -> Vec<Stmt> {
    vec![
        s_return(e_static_call("DateTime", "__elephc_fr_to_sdn", vec![e_var("year"), e_var("month"), e_var("day")])),
    ]
}

/// Reproduces `FR_TO_SDN_SRC`.
pub(super) fn fr_to_sdn() -> Vec<Stmt> {
    vec![
        s_if(
            e_binop(e_binop(e_binop(e_binop(e_binop(e_binop(e_var("y"), BinOp::Lt, e_int(1)), BinOp::Or, e_binop(e_var("y"), BinOp::Gt, e_int(14))), BinOp::Or, e_binop(e_var("m"), BinOp::Lt, e_int(1))), BinOp::Or, e_binop(e_var("m"), BinOp::Gt, e_int(13))), BinOp::Or, e_binop(e_var("d"), BinOp::Lt, e_int(1))), BinOp::Or, e_binop(e_var("d"), BinOp::Gt, e_int(30))),
            vec![
                s_return(e_int(0)),
            ],
            vec![],
            None,
        ),
        s_return(e_binop(e_binop(e_binop(e_call("intdiv", vec![e_binop(e_var("y"), BinOp::Mul, e_int(1461)), e_int(4)]), BinOp::Add, e_binop(e_binop(e_var("m"), BinOp::Sub, e_int(1)), BinOp::Mul, e_int(30))), BinOp::Add, e_var("d")), BinOp::Add, e_int(2375474))),
    ]
}

/// Reproduces `GREGORIANTOJD_SRC`.
pub(super) fn gregoriantojd() -> Vec<Stmt> {
    vec![
        s_return(e_static_call("DateTime", "__elephc_greg_to_sdn", vec![e_var("year"), e_var("month"), e_var("day")])),
    ]
}

/// Reproduces `GREG_TO_SDN_SRC`.
pub(super) fn greg_to_sdn() -> Vec<Stmt> {
    vec![
        s_if(
            e_binop(e_binop(e_binop(e_binop(e_binop(e_binop(e_var("iy"), BinOp::Eq, e_int(0)), BinOp::Or, e_binop(e_var("iy"), BinOp::Lt, e_neg(e_int(4714)))), BinOp::Or, e_binop(e_var("im"), BinOp::LtEq, e_int(0))), BinOp::Or, e_binop(e_var("im"), BinOp::Gt, e_int(12))), BinOp::Or, e_binop(e_var("id"), BinOp::LtEq, e_int(0))), BinOp::Or, e_binop(e_var("id"), BinOp::Gt, e_int(31))),
            vec![
                s_return(e_int(0)),
            ],
            vec![],
            None,
        ),
        s_if(
            e_binop(e_var("iy"), BinOp::Eq, e_neg(e_int(4714))),
            vec![
                s_if(
                    e_binop(e_var("im"), BinOp::Lt, e_int(11)),
                    vec![
                        s_return(e_int(0)),
                    ],
                    vec![],
                    None,
                ),
                s_if(
                    e_binop(e_binop(e_var("im"), BinOp::Eq, e_int(11)), BinOp::And, e_binop(e_var("id"), BinOp::Lt, e_int(25))),
                    vec![
                        s_return(e_int(0)),
                    ],
                    vec![],
                    None,
                ),
            ],
            vec![],
            None,
        ),
        s_assign("year", e_ternary(e_binop(e_var("iy"), BinOp::Lt, e_int(0)), e_binop(e_var("iy"), BinOp::Add, e_int(4801)), e_binop(e_var("iy"), BinOp::Add, e_int(4800)))),
        s_if(
            e_binop(e_var("im"), BinOp::Gt, e_int(2)),
            vec![
                s_assign("month", e_binop(e_var("im"), BinOp::Sub, e_int(3))),
            ],
            vec![],
            Some(vec![
            s_assign("month", e_binop(e_var("im"), BinOp::Add, e_int(9))),
            s_assign("year", e_binop(e_var("year"), BinOp::Sub, e_int(1))),
        ]),
        ),
        s_return(e_binop(e_binop(e_binop(e_binop(e_call("intdiv", vec![e_binop(e_call("intdiv", vec![e_var("year"), e_int(100)]), BinOp::Mul, e_int(146097)), e_int(4)]), BinOp::Add, e_call("intdiv", vec![e_binop(e_binop(e_var("year"), BinOp::Mod, e_int(100)), BinOp::Mul, e_int(1461)), e_int(4)])), BinOp::Add, e_call("intdiv", vec![e_binop(e_binop(e_var("month"), BinOp::Mul, e_int(153)), BinOp::Add, e_int(2)), e_int(5)])), BinOp::Add, e_var("id")), BinOp::Sub, e_int(32045))),
    ]
}

/// Reproduces `JDDAYOFWEEK_SRC`.
pub(super) fn jddayofweek() -> Vec<Stmt> {
    vec![
        s_assign("d", e_binop(e_binop(e_binop(e_var("jd"), BinOp::Mod, e_int(7)), BinOp::Add, e_int(8)), BinOp::Mod, e_int(7))),
        s_assign("long", e_array(vec![e_str("Sunday"), e_str("Monday"), e_str("Tuesday"), e_str("Wednesday"), e_str("Thursday"), e_str("Friday"), e_str("Saturday")])),
        s_assign("short", e_array(vec![e_str("Sun"), e_str("Mon"), e_str("Tue"), e_str("Wed"), e_str("Thu"), e_str("Fri"), e_str("Sat")])),
        s_if(
            e_binop(e_var("mode"), BinOp::Eq, e_int(1)),
            vec![
                s_return(e_index(e_var("long"), e_var("d"))),
            ],
            vec![],
            None,
        ),
        s_if(
            e_binop(e_var("mode"), BinOp::Eq, e_int(2)),
            vec![
                s_return(e_index(e_var("short"), e_var("d"))),
            ],
            vec![],
            None,
        ),
        s_return(e_var("d")),
    ]
}

/// Reproduces `JDMONTHNAME_SRC`.
pub(super) fn jdmonthname() -> Vec<Stmt> {
    vec![
        s_assign("gregShort", e_array(vec![e_str(""), e_str("Jan"), e_str("Feb"), e_str("Mar"), e_str("Apr"), e_str("May"), e_str("Jun"), e_str("Jul"), e_str("Aug"), e_str("Sep"), e_str("Oct"), e_str("Nov"), e_str("Dec")])),
        s_assign("gregLong", e_array(vec![e_str(""), e_str("January"), e_str("February"), e_str("March"), e_str("April"), e_str("May"), e_str("June"), e_str("July"), e_str("August"), e_str("September"), e_str("October"), e_str("November"), e_str("December")])),
        s_assign("french", e_array(vec![e_str(""), e_str("Vendemiaire"), e_str("Brumaire"), e_str("Frimaire"), e_str("Nivose"), e_str("Pluviose"), e_str("Ventose"), e_str("Germinal"), e_str("Floreal"), e_str("Prairial"), e_str("Messidor"), e_str("Thermidor"), e_str("Fructidor"), e_str("Extra")])),
        s_if(
            e_binop(e_var("mode"), BinOp::Eq, e_int(1)),
            vec![
                s_assign("r", e_static_call("DateTime", "__elephc_sdn_to_greg", vec![e_var("jd")])),
                s_return(e_index(e_var("gregLong"), e_index(e_var("r"), e_str("m")))),
            ],
            vec![],
            None,
        ),
        s_if(
            e_binop(e_var("mode"), BinOp::Eq, e_int(2)),
            vec![
                s_assign("r", e_static_call("DateTime", "__elephc_sdn_to_jul", vec![e_var("jd")])),
                s_return(e_index(e_var("gregShort"), e_index(e_var("r"), e_str("m")))),
            ],
            vec![],
            None,
        ),
        s_if(
            e_binop(e_var("mode"), BinOp::Eq, e_int(3)),
            vec![
                s_assign("r", e_static_call("DateTime", "__elephc_sdn_to_jul", vec![e_var("jd")])),
                s_return(e_index(e_var("gregLong"), e_index(e_var("r"), e_str("m")))),
            ],
            vec![],
            None,
        ),
        s_if(
            e_binop(e_var("mode"), BinOp::Eq, e_int(4)),
            vec![
                s_assign("r", e_static_call("DateTime", "__elephc_sdn_to_jew", vec![e_var("jd")])),
                s_return(e_ternary(e_binop(e_index(e_var("r"), e_str("y")), BinOp::Gt, e_int(0)), e_static_call("DateTime", "__elephc_jew_month_name", vec![e_index(e_var("r"), e_str("y")), e_index(e_var("r"), e_str("m"))]), e_str(""))),
            ],
            vec![],
            None,
        ),
        s_if(
            e_binop(e_var("mode"), BinOp::Eq, e_int(5)),
            vec![
                s_assign("r", e_static_call("DateTime", "__elephc_sdn_to_fr", vec![e_var("jd")])),
                s_return(e_index(e_var("french"), e_index(e_var("r"), e_str("m")))),
            ],
            vec![],
            None,
        ),
        s_assign("r", e_static_call("DateTime", "__elephc_sdn_to_greg", vec![e_var("jd")])),
        s_return(e_index(e_var("gregShort"), e_index(e_var("r"), e_str("m")))),
    ]
}

/// Reproduces `JDTOFRENCH_SRC`.
pub(super) fn jdtofrench() -> Vec<Stmt> {
    vec![
        s_assign("r", e_static_call("DateTime", "__elephc_sdn_to_fr", vec![e_var("jd")])),
        s_return(e_binop(e_binop(e_binop(e_binop(e_index(e_var("r"), e_str("m")), BinOp::Concat, e_str("/")), BinOp::Concat, e_index(e_var("r"), e_str("d"))), BinOp::Concat, e_str("/")), BinOp::Concat, e_index(e_var("r"), e_str("y")))),
    ]
}

/// Reproduces `JDTOGREGORIAN_SRC`.
pub(super) fn jdtogregorian() -> Vec<Stmt> {
    vec![
        s_assign("r", e_static_call("DateTime", "__elephc_sdn_to_greg", vec![e_var("jd")])),
        s_return(e_binop(e_binop(e_binop(e_binop(e_index(e_var("r"), e_str("m")), BinOp::Concat, e_str("/")), BinOp::Concat, e_index(e_var("r"), e_str("d"))), BinOp::Concat, e_str("/")), BinOp::Concat, e_index(e_var("r"), e_str("y")))),
    ]
}

/// Reproduces `JDTOJEWISH_SRC`.
pub(super) fn jdtojewish() -> Vec<Stmt> {
    vec![
        s_assign("r", e_static_call("DateTime", "__elephc_sdn_to_jew", vec![e_var("jd")])),
        s_return(e_binop(e_binop(e_binop(e_binop(e_index(e_var("r"), e_str("m")), BinOp::Concat, e_str("/")), BinOp::Concat, e_index(e_var("r"), e_str("d"))), BinOp::Concat, e_str("/")), BinOp::Concat, e_index(e_var("r"), e_str("y")))),
    ]
}

/// Reproduces `JDTOJULIAN_SRC`.
pub(super) fn jdtojulian() -> Vec<Stmt> {
    vec![
        s_assign("r", e_static_call("DateTime", "__elephc_sdn_to_jul", vec![e_var("jd")])),
        s_return(e_binop(e_binop(e_binop(e_binop(e_index(e_var("r"), e_str("m")), BinOp::Concat, e_str("/")), BinOp::Concat, e_index(e_var("r"), e_str("d"))), BinOp::Concat, e_str("/")), BinOp::Concat, e_index(e_var("r"), e_str("y")))),
    ]
}

/// Reproduces `JDTOUNIX_SRC`.
pub(super) fn jdtounix() -> Vec<Stmt> {
    vec![
        s_return(e_binop(e_binop(e_var("jd"), BinOp::Sub, e_int(2440588)), BinOp::Mul, e_int(86400))),
    ]
}

/// Reproduces `JEWISHTOJD_SRC`.
pub(super) fn jewishtojd() -> Vec<Stmt> {
    vec![
        s_return(e_static_call("DateTime", "__elephc_jew_to_sdn", vec![e_var("year"), e_var("month"), e_var("day")])),
    ]
}

/// Reproduces `JEW_FIND_START_YEAR_SRC`.
pub(super) fn jew_find_start_year() -> Vec<Stmt> {
    vec![
        s_assign("offsets", e_array(vec![e_int(0), e_int(12), e_int(24), e_int(37), e_int(49), e_int(61), e_int(74), e_int(86), e_int(99), e_int(111), e_int(123), e_int(136), e_int(148), e_int(160), e_int(173), e_int(185), e_int(197), e_int(210), e_int(222)])),
        s_assign("mc", e_call("intdiv", vec![e_binop(e_var("year"), BinOp::Sub, e_int(1)), e_int(19)])),
        s_assign("my", e_binop(e_binop(e_var("year"), BinOp::Sub, e_int(1)), BinOp::Mod, e_int(19))),
        s_assign("mm", e_static_call("DateTime", "__elephc_jew_molad_cycle", vec![e_var("mc")])),
        s_assign("md", e_index(e_var("mm"), e_str("md"))),
        s_assign("mh", e_index(e_var("mm"), e_str("mh"))),
        s_assign("mh", e_binop(e_var("mh"), BinOp::Add, e_binop(e_int(765433), BinOp::Mul, e_index(e_var("offsets"), e_var("my"))))),
        s_assign("md", e_binop(e_var("md"), BinOp::Add, e_call("intdiv", vec![e_var("mh"), e_int(25920)]))),
        s_assign("mh", e_binop(e_var("mh"), BinOp::Mod, e_int(25920))),
        s_assign("t1", e_static_call("DateTime", "__elephc_jew_tishri1", vec![e_var("my"), e_var("md"), e_var("mh")])),
        s_return(e_array_assoc(vec![(e_str("mc"), e_var("mc")), (e_str("my"), e_var("my")), (e_str("md"), e_var("md")), (e_str("mh"), e_var("mh")), (e_str("t1"), e_var("t1"))])),
    ]
}

/// Reproduces `JEW_FIND_TISHRI_MOLAD_SRC`.
pub(super) fn jew_find_tishri_molad() -> Vec<Stmt> {
    vec![
        s_assign("months", e_array(vec![e_int(12), e_int(12), e_int(13), e_int(12), e_int(12), e_int(13), e_int(12), e_int(13), e_int(12), e_int(12), e_int(13), e_int(12), e_int(12), e_int(13), e_int(12), e_int(12), e_int(13), e_int(12), e_int(13)])),
        s_assign("mc", e_call("intdiv", vec![e_binop(e_var("inputDay"), BinOp::Add, e_int(310)), e_int(6940)])),
        s_assign("mm", e_static_call("DateTime", "__elephc_jew_molad_cycle", vec![e_var("mc")])),
        s_assign("md", e_index(e_var("mm"), e_str("md"))),
        s_assign("mh", e_index(e_var("mm"), e_str("mh"))),
        s_while(e_binop(e_var("md"), BinOp::Lt, e_binop(e_binop(e_var("inputDay"), BinOp::Sub, e_int(6940)), BinOp::Add, e_int(310))), vec![
            s_assign("mc", e_binop(e_var("mc"), BinOp::Add, e_int(1))),
            s_assign("mh", e_binop(e_var("mh"), BinOp::Add, e_int(179876755))),
            s_assign("md", e_binop(e_var("md"), BinOp::Add, e_call("intdiv", vec![e_var("mh"), e_int(25920)]))),
            s_assign("mh", e_binop(e_var("mh"), BinOp::Mod, e_int(25920))),
        ]),
        s_assign("my", e_int(0)),
        s_while(e_binop(e_var("my"), BinOp::Lt, e_int(18)), vec![
            s_if(
                e_binop(e_var("md"), BinOp::Gt, e_binop(e_var("inputDay"), BinOp::Sub, e_int(74))),
                vec![
                    s_break(1),
                ],
                vec![],
                None,
            ),
            s_assign("mh", e_binop(e_var("mh"), BinOp::Add, e_binop(e_int(765433), BinOp::Mul, e_index(e_var("months"), e_var("my"))))),
            s_assign("md", e_binop(e_var("md"), BinOp::Add, e_call("intdiv", vec![e_var("mh"), e_int(25920)]))),
            s_assign("mh", e_binop(e_var("mh"), BinOp::Mod, e_int(25920))),
            s_assign("my", e_binop(e_var("my"), BinOp::Add, e_int(1))),
        ]),
        s_return(e_array_assoc(vec![(e_str("mc"), e_var("mc")), (e_str("my"), e_var("my")), (e_str("md"), e_var("md")), (e_str("mh"), e_var("mh"))])),
    ]
}

/// Reproduces `JEW_MOLAD_CYCLE_SRC`.
pub(super) fn jew_molad_cycle() -> Vec<Stmt> {
    vec![
        s_assign("total", e_binop(e_int(31524), BinOp::Add, e_binop(e_var("mc"), BinOp::Mul, e_int(179876755)))),
        s_return(e_array_assoc(vec![(e_str("md"), e_call("intdiv", vec![e_var("total"), e_int(25920)])), (e_str("mh"), e_binop(e_var("total"), BinOp::Mod, e_int(25920)))])),
    ]
}

/// Reproduces `JEW_MONTH_NAME_SRC`.
pub(super) fn jew_month_name() -> Vec<Stmt> {
    vec![
        s_assign("months", e_array(vec![e_int(12), e_int(12), e_int(13), e_int(12), e_int(12), e_int(13), e_int(12), e_int(13), e_int(12), e_int(12), e_int(13), e_int(12), e_int(12), e_int(13), e_int(12), e_int(12), e_int(13), e_int(12), e_int(13)])),
        s_assign("leapYear", e_binop(e_index(e_var("months"), e_binop(e_binop(e_var("year"), BinOp::Sub, e_int(1)), BinOp::Mod, e_int(19))), BinOp::Eq, e_int(13))),
        s_assign("leap", e_array(vec![e_str(""), e_str("Tishri"), e_str("Heshvan"), e_str("Kislev"), e_str("Tevet"), e_str("Shevat"), e_str("Adar I"), e_str("Adar II"), e_str("Nisan"), e_str("Iyyar"), e_str("Sivan"), e_str("Tammuz"), e_str("Av"), e_str("Elul")])),
        s_assign("reg", e_array(vec![e_str(""), e_str("Tishri"), e_str("Heshvan"), e_str("Kislev"), e_str("Tevet"), e_str("Shevat"), e_str(""), e_str("Adar"), e_str("Nisan"), e_str("Iyyar"), e_str("Sivan"), e_str("Tammuz"), e_str("Av"), e_str("Elul")])),
        s_return(e_ternary(e_var("leapYear"), e_index(e_var("leap"), e_var("month")), e_index(e_var("reg"), e_var("month")))),
    ]
}

/// Reproduces `JEW_TISHRI1_SRC`.
pub(super) fn jew_tishri1() -> Vec<Stmt> {
    vec![
        s_assign("tishri1", e_var("moladDay")),
        s_assign("dow", e_binop(e_var("tishri1"), BinOp::Mod, e_int(7))),
        s_assign("leap", e_binop(e_binop(e_binop(e_binop(e_binop(e_binop(e_binop(e_var("my"), BinOp::Eq, e_int(2)), BinOp::Or, e_binop(e_var("my"), BinOp::Eq, e_int(5))), BinOp::Or, e_binop(e_var("my"), BinOp::Eq, e_int(7))), BinOp::Or, e_binop(e_var("my"), BinOp::Eq, e_int(10))), BinOp::Or, e_binop(e_var("my"), BinOp::Eq, e_int(13))), BinOp::Or, e_binop(e_var("my"), BinOp::Eq, e_int(16))), BinOp::Or, e_binop(e_var("my"), BinOp::Eq, e_int(18)))),
        s_assign("lastLeap", e_binop(e_binop(e_binop(e_binop(e_binop(e_binop(e_binop(e_var("my"), BinOp::Eq, e_int(3)), BinOp::Or, e_binop(e_var("my"), BinOp::Eq, e_int(6))), BinOp::Or, e_binop(e_var("my"), BinOp::Eq, e_int(8))), BinOp::Or, e_binop(e_var("my"), BinOp::Eq, e_int(11))), BinOp::Or, e_binop(e_var("my"), BinOp::Eq, e_int(14))), BinOp::Or, e_binop(e_var("my"), BinOp::Eq, e_int(17))), BinOp::Or, e_binop(e_var("my"), BinOp::Eq, e_int(0)))),
        s_if(
            e_binop(e_binop(e_binop(e_var("moladHalakim"), BinOp::GtEq, e_int(19440)), BinOp::Or, e_binop(e_binop(e_not(e_var("leap")), BinOp::And, e_binop(e_var("dow"), BinOp::Eq, e_int(2))), BinOp::And, e_binop(e_var("moladHalakim"), BinOp::GtEq, e_int(9924)))), BinOp::Or, e_binop(e_binop(e_var("lastLeap"), BinOp::And, e_binop(e_var("dow"), BinOp::Eq, e_int(1))), BinOp::And, e_binop(e_var("moladHalakim"), BinOp::GtEq, e_int(16789)))),
            vec![
                s_assign("tishri1", e_binop(e_var("tishri1"), BinOp::Add, e_int(1))),
                s_assign("dow", e_binop(e_var("dow"), BinOp::Add, e_int(1))),
                s_if(
                    e_binop(e_var("dow"), BinOp::Eq, e_int(7)),
                    vec![
                        s_assign("dow", e_int(0)),
                    ],
                    vec![],
                    None,
                ),
            ],
            vec![],
            None,
        ),
        s_if(
            e_binop(e_binop(e_binop(e_var("dow"), BinOp::Eq, e_int(3)), BinOp::Or, e_binop(e_var("dow"), BinOp::Eq, e_int(5))), BinOp::Or, e_binop(e_var("dow"), BinOp::Eq, e_int(0))),
            vec![
                s_assign("tishri1", e_binop(e_var("tishri1"), BinOp::Add, e_int(1))),
            ],
            vec![],
            None,
        ),
        s_return(e_var("tishri1")),
    ]
}

/// Reproduces `JEW_TO_SDN_SRC`.
pub(super) fn jew_to_sdn() -> Vec<Stmt> {
    vec![
        s_if(
            e_binop(e_binop(e_binop(e_var("year"), BinOp::LtEq, e_int(0)), BinOp::Or, e_binop(e_var("day"), BinOp::LtEq, e_int(0))), BinOp::Or, e_binop(e_var("day"), BinOp::Gt, e_int(30))),
            vec![
                s_return(e_int(0)),
            ],
            vec![],
            None,
        ),
        s_assign("months", e_array(vec![e_int(12), e_int(12), e_int(13), e_int(12), e_int(12), e_int(13), e_int(12), e_int(13), e_int(12), e_int(12), e_int(13), e_int(12), e_int(12), e_int(13), e_int(12), e_int(12), e_int(13), e_int(12), e_int(13)])),
        s_if(
            e_binop(e_binop(e_var("month"), BinOp::Eq, e_int(1)), BinOp::Or, e_binop(e_var("month"), BinOp::Eq, e_int(2))),
            vec![
                s_assign("s", e_static_call("DateTime", "__elephc_jew_find_start_year", vec![e_var("year")])),
                s_assign("t1", e_index(e_var("s"), e_str("t1"))),
                s_assign("sdn", e_ternary(e_binop(e_var("month"), BinOp::Eq, e_int(1)), e_binop(e_binop(e_var("t1"), BinOp::Add, e_var("day")), BinOp::Sub, e_int(1)), e_binop(e_binop(e_var("t1"), BinOp::Add, e_var("day")), BinOp::Add, e_int(29)))),
            ],
            vec![],
            Some(vec![
            s_if(
                e_binop(e_var("month"), BinOp::Eq, e_int(3)),
                vec![
                    s_assign("s", e_static_call("DateTime", "__elephc_jew_find_start_year", vec![e_var("year")])),
                    s_assign("t1", e_index(e_var("s"), e_str("t1"))),
                    s_assign("md", e_index(e_var("s"), e_str("md"))),
                    s_assign("mh", e_index(e_var("s"), e_str("mh"))),
                    s_assign("my", e_index(e_var("s"), e_str("my"))),
                    s_assign("mh", e_binop(e_var("mh"), BinOp::Add, e_binop(e_int(765433), BinOp::Mul, e_index(e_var("months"), e_var("my"))))),
                    s_assign("md", e_binop(e_var("md"), BinOp::Add, e_call("intdiv", vec![e_var("mh"), e_int(25920)]))),
                    s_assign("mh", e_binop(e_var("mh"), BinOp::Mod, e_int(25920))),
                    s_assign("t1a", e_static_call("DateTime", "__elephc_jew_tishri1", vec![e_binop(e_binop(e_var("my"), BinOp::Add, e_int(1)), BinOp::Mod, e_int(19)), e_var("md"), e_var("mh")])),
                    s_assign("yl", e_binop(e_var("t1a"), BinOp::Sub, e_var("t1"))),
                    s_assign("sdn", e_ternary(e_binop(e_binop(e_var("yl"), BinOp::Eq, e_int(355)), BinOp::Or, e_binop(e_var("yl"), BinOp::Eq, e_int(385))), e_binop(e_binop(e_var("t1"), BinOp::Add, e_var("day")), BinOp::Add, e_int(59)), e_binop(e_binop(e_var("t1"), BinOp::Add, e_var("day")), BinOp::Add, e_int(58)))),
                ],
                vec![],
                Some(vec![
                s_if(
                    e_binop(e_binop(e_binop(e_var("month"), BinOp::Eq, e_int(4)), BinOp::Or, e_binop(e_var("month"), BinOp::Eq, e_int(5))), BinOp::Or, e_binop(e_var("month"), BinOp::Eq, e_int(6))),
                    vec![
                        s_assign("s", e_static_call("DateTime", "__elephc_jew_find_start_year", vec![e_binop(e_var("year"), BinOp::Add, e_int(1))])),
                        s_assign("t1a", e_index(e_var("s"), e_str("t1"))),
                        s_assign("lai", e_ternary(e_binop(e_index(e_var("months"), e_binop(e_binop(e_var("year"), BinOp::Sub, e_int(1)), BinOp::Mod, e_int(19))), BinOp::Eq, e_int(12)), e_int(29), e_int(59))),
                        s_if(
                            e_binop(e_var("month"), BinOp::Eq, e_int(4)),
                            vec![
                                s_assign("sdn", e_binop(e_binop(e_binop(e_var("t1a"), BinOp::Add, e_var("day")), BinOp::Sub, e_var("lai")), BinOp::Sub, e_int(237))),
                            ],
                            vec![],
                            Some(vec![
                            s_if(
                                e_binop(e_var("month"), BinOp::Eq, e_int(5)),
                                vec![
                                    s_assign("sdn", e_binop(e_binop(e_binop(e_var("t1a"), BinOp::Add, e_var("day")), BinOp::Sub, e_var("lai")), BinOp::Sub, e_int(208))),
                                ],
                                vec![],
                                Some(vec![
                                s_assign("sdn", e_binop(e_binop(e_binop(e_var("t1a"), BinOp::Add, e_var("day")), BinOp::Sub, e_var("lai")), BinOp::Sub, e_int(178))),
                            ]),
                            ),
                        ]),
                        ),
                    ],
                    vec![],
                    Some(vec![
                    s_assign("s", e_static_call("DateTime", "__elephc_jew_find_start_year", vec![e_binop(e_var("year"), BinOp::Add, e_int(1))])),
                    s_assign("t1a", e_index(e_var("s"), e_str("t1"))),
                    s_if(
                        e_binop(e_var("month"), BinOp::Eq, e_int(7)),
                        vec![
                            s_assign("sdn", e_binop(e_binop(e_var("t1a"), BinOp::Add, e_var("day")), BinOp::Sub, e_int(207))),
                        ],
                        vec![],
                        Some(vec![
                        s_if(
                            e_binop(e_var("month"), BinOp::Eq, e_int(8)),
                            vec![
                                s_assign("sdn", e_binop(e_binop(e_var("t1a"), BinOp::Add, e_var("day")), BinOp::Sub, e_int(178))),
                            ],
                            vec![],
                            Some(vec![
                            s_if(
                                e_binop(e_var("month"), BinOp::Eq, e_int(9)),
                                vec![
                                    s_assign("sdn", e_binop(e_binop(e_var("t1a"), BinOp::Add, e_var("day")), BinOp::Sub, e_int(148))),
                                ],
                                vec![],
                                Some(vec![
                                s_if(
                                    e_binop(e_var("month"), BinOp::Eq, e_int(10)),
                                    vec![
                                        s_assign("sdn", e_binop(e_binop(e_var("t1a"), BinOp::Add, e_var("day")), BinOp::Sub, e_int(119))),
                                    ],
                                    vec![],
                                    Some(vec![
                                    s_if(
                                        e_binop(e_var("month"), BinOp::Eq, e_int(11)),
                                        vec![
                                            s_assign("sdn", e_binop(e_binop(e_var("t1a"), BinOp::Add, e_var("day")), BinOp::Sub, e_int(89))),
                                        ],
                                        vec![],
                                        Some(vec![
                                        s_if(
                                            e_binop(e_var("month"), BinOp::Eq, e_int(12)),
                                            vec![
                                                s_assign("sdn", e_binop(e_binop(e_var("t1a"), BinOp::Add, e_var("day")), BinOp::Sub, e_int(60))),
                                            ],
                                            vec![],
                                            Some(vec![
                                            s_if(
                                                e_binop(e_var("month"), BinOp::Eq, e_int(13)),
                                                vec![
                                                    s_assign("sdn", e_binop(e_binop(e_var("t1a"), BinOp::Add, e_var("day")), BinOp::Sub, e_int(30))),
                                                ],
                                                vec![],
                                                Some(vec![
                                                s_return(e_int(0)),
                                            ]),
                                            ),
                                        ]),
                                        ),
                                    ]),
                                    ),
                                ]),
                                ),
                            ]),
                            ),
                        ]),
                        ),
                    ]),
                    ),
                ]),
                ),
            ]),
            ),
        ]),
        ),
        s_return(e_binop(e_var("sdn"), BinOp::Add, e_int(347997))),
    ]
}

/// Reproduces `JULIANTOJD_SRC`.
pub(super) fn juliantojd() -> Vec<Stmt> {
    vec![
        s_return(e_static_call("DateTime", "__elephc_jul_to_sdn", vec![e_var("year"), e_var("month"), e_var("day")])),
    ]
}

/// Reproduces `JUL_TO_SDN_SRC`.
pub(super) fn jul_to_sdn() -> Vec<Stmt> {
    vec![
        s_if(
            e_binop(e_binop(e_binop(e_binop(e_binop(e_binop(e_var("iy"), BinOp::Eq, e_int(0)), BinOp::Or, e_binop(e_var("iy"), BinOp::Lt, e_neg(e_int(4713)))), BinOp::Or, e_binop(e_var("im"), BinOp::LtEq, e_int(0))), BinOp::Or, e_binop(e_var("im"), BinOp::Gt, e_int(12))), BinOp::Or, e_binop(e_var("id"), BinOp::LtEq, e_int(0))), BinOp::Or, e_binop(e_var("id"), BinOp::Gt, e_int(31))),
            vec![
                s_return(e_int(0)),
            ],
            vec![],
            None,
        ),
        s_if(
            e_binop(e_var("iy"), BinOp::Eq, e_neg(e_int(4713))),
            vec![
                s_if(
                    e_binop(e_binop(e_var("im"), BinOp::Eq, e_int(1)), BinOp::And, e_binop(e_var("id"), BinOp::Eq, e_int(1))),
                    vec![
                        s_return(e_int(0)),
                    ],
                    vec![],
                    None,
                ),
            ],
            vec![],
            None,
        ),
        s_assign("year", e_ternary(e_binop(e_var("iy"), BinOp::Lt, e_int(0)), e_binop(e_var("iy"), BinOp::Add, e_int(4801)), e_binop(e_var("iy"), BinOp::Add, e_int(4800)))),
        s_if(
            e_binop(e_var("im"), BinOp::Gt, e_int(2)),
            vec![
                s_assign("month", e_binop(e_var("im"), BinOp::Sub, e_int(3))),
            ],
            vec![],
            Some(vec![
            s_assign("month", e_binop(e_var("im"), BinOp::Add, e_int(9))),
            s_assign("year", e_binop(e_var("year"), BinOp::Sub, e_int(1))),
        ]),
        ),
        s_return(e_binop(e_binop(e_binop(e_call("intdiv", vec![e_binop(e_var("year"), BinOp::Mul, e_int(1461)), e_int(4)]), BinOp::Add, e_call("intdiv", vec![e_binop(e_binop(e_var("month"), BinOp::Mul, e_int(153)), BinOp::Add, e_int(2)), e_int(5)])), BinOp::Add, e_var("id")), BinOp::Sub, e_int(32083))),
    ]
}

/// Reproduces `SDN_TO_FR_SRC`.
pub(super) fn sdn_to_fr() -> Vec<Stmt> {
    vec![
        s_if(
            e_binop(e_binop(e_var("sdn"), BinOp::Lt, e_int(2375840)), BinOp::Or, e_binop(e_var("sdn"), BinOp::Gt, e_int(2380952))),
            vec![
                s_return(e_array_assoc(vec![(e_str("y"), e_int(0)), (e_str("m"), e_int(0)), (e_str("d"), e_int(0))])),
            ],
            vec![],
            None,
        ),
        s_assign("temp", e_binop(e_binop(e_binop(e_var("sdn"), BinOp::Sub, e_int(2375474)), BinOp::Mul, e_int(4)), BinOp::Sub, e_int(1))),
        s_assign("year", e_call("intdiv", vec![e_var("temp"), e_int(1461)])),
        s_assign("doy", e_call("intdiv", vec![e_binop(e_var("temp"), BinOp::Mod, e_int(1461)), e_int(4)])),
        s_assign("month", e_binop(e_call("intdiv", vec![e_var("doy"), e_int(30)]), BinOp::Add, e_int(1))),
        s_assign("day", e_binop(e_binop(e_var("doy"), BinOp::Mod, e_int(30)), BinOp::Add, e_int(1))),
        s_return(e_array_assoc(vec![(e_str("y"), e_var("year")), (e_str("m"), e_var("month")), (e_str("d"), e_var("day"))])),
    ]
}

/// Reproduces `SDN_TO_GREG_SRC`.
pub(super) fn sdn_to_greg() -> Vec<Stmt> {
    vec![
        s_if(
            e_binop(e_var("sdn"), BinOp::LtEq, e_int(0)),
            vec![
                s_return(e_array_assoc(vec![(e_str("y"), e_int(0)), (e_str("m"), e_int(0)), (e_str("d"), e_int(0))])),
            ],
            vec![],
            None,
        ),
        s_assign("temp", e_binop(e_binop(e_binop(e_var("sdn"), BinOp::Add, e_int(32045)), BinOp::Mul, e_int(4)), BinOp::Sub, e_int(1))),
        s_assign("century", e_call("intdiv", vec![e_var("temp"), e_int(146097)])),
        s_assign("temp", e_binop(e_binop(e_call("intdiv", vec![e_binop(e_var("temp"), BinOp::Mod, e_int(146097)), e_int(4)]), BinOp::Mul, e_int(4)), BinOp::Add, e_int(3))),
        s_assign("year", e_binop(e_binop(e_var("century"), BinOp::Mul, e_int(100)), BinOp::Add, e_call("intdiv", vec![e_var("temp"), e_int(1461)]))),
        s_assign("doy", e_binop(e_call("intdiv", vec![e_binop(e_var("temp"), BinOp::Mod, e_int(1461)), e_int(4)]), BinOp::Add, e_int(1))),
        s_assign("temp", e_binop(e_binop(e_var("doy"), BinOp::Mul, e_int(5)), BinOp::Sub, e_int(3))),
        s_assign("month", e_call("intdiv", vec![e_var("temp"), e_int(153)])),
        s_assign("day", e_binop(e_call("intdiv", vec![e_binop(e_var("temp"), BinOp::Mod, e_int(153)), e_int(5)]), BinOp::Add, e_int(1))),
        s_if(
            e_binop(e_var("month"), BinOp::Lt, e_int(10)),
            vec![
                s_assign("month", e_binop(e_var("month"), BinOp::Add, e_int(3))),
            ],
            vec![],
            Some(vec![
            s_assign("year", e_binop(e_var("year"), BinOp::Add, e_int(1))),
            s_assign("month", e_binop(e_var("month"), BinOp::Sub, e_int(9))),
        ]),
        ),
        s_assign("year", e_binop(e_var("year"), BinOp::Sub, e_int(4800))),
        s_if(
            e_binop(e_var("year"), BinOp::LtEq, e_int(0)),
            vec![
                s_assign("year", e_binop(e_var("year"), BinOp::Sub, e_int(1))),
            ],
            vec![],
            None,
        ),
        s_return(e_array_assoc(vec![(e_str("y"), e_var("year")), (e_str("m"), e_var("month")), (e_str("d"), e_var("day"))])),
    ]
}

/// Reproduces `SDN_TO_JEW_SRC`.
pub(super) fn sdn_to_jew() -> Vec<Stmt> {
    vec![
        s_if(
            e_binop(e_binop(e_var("sdn"), BinOp::LtEq, e_int(347997)), BinOp::Or, e_binop(e_var("sdn"), BinOp::Gt, e_int(324542846))),
            vec![
                s_return(e_array_assoc(vec![(e_str("y"), e_int(0)), (e_str("m"), e_int(0)), (e_str("d"), e_int(0))])),
            ],
            vec![],
            None,
        ),
        s_assign("months", e_array(vec![e_int(12), e_int(12), e_int(13), e_int(12), e_int(12), e_int(13), e_int(12), e_int(13), e_int(12), e_int(12), e_int(13), e_int(12), e_int(12), e_int(13), e_int(12), e_int(12), e_int(13), e_int(12), e_int(13)])),
        s_assign("inputDay", e_binop(e_var("sdn"), BinOp::Sub, e_int(347997))),
        s_assign("f", e_static_call("DateTime", "__elephc_jew_find_tishri_molad", vec![e_var("inputDay")])),
        s_assign("mc", e_index(e_var("f"), e_str("mc"))),
        s_assign("my", e_index(e_var("f"), e_str("my"))),
        s_assign("day", e_index(e_var("f"), e_str("md"))),
        s_assign("hal", e_index(e_var("f"), e_str("mh"))),
        s_assign("t1", e_static_call("DateTime", "__elephc_jew_tishri1", vec![e_var("my"), e_var("day"), e_var("hal")])),
        s_assign("t1a", e_int(0)),
        s_assign("py", e_int(0)),
        s_assign("pm", e_int(0)),
        s_assign("pd", e_int(0)),
        s_if(
            e_binop(e_var("inputDay"), BinOp::GtEq, e_var("t1")),
            vec![
                s_assign("py", e_binop(e_binop(e_binop(e_var("mc"), BinOp::Mul, e_int(19)), BinOp::Add, e_var("my")), BinOp::Add, e_int(1))),
                s_if(
                    e_binop(e_var("inputDay"), BinOp::Lt, e_binop(e_var("t1"), BinOp::Add, e_int(59))),
                    vec![
                        s_if(
                            e_binop(e_var("inputDay"), BinOp::Lt, e_binop(e_var("t1"), BinOp::Add, e_int(30))),
                            vec![
                                s_return(e_array_assoc(vec![(e_str("y"), e_var("py")), (e_str("m"), e_int(1)), (e_str("d"), e_binop(e_binop(e_var("inputDay"), BinOp::Sub, e_var("t1")), BinOp::Add, e_int(1)))])),
                            ],
                            vec![],
                            None,
                        ),
                        s_return(e_array_assoc(vec![(e_str("y"), e_var("py")), (e_str("m"), e_int(2)), (e_str("d"), e_binop(e_binop(e_var("inputDay"), BinOp::Sub, e_var("t1")), BinOp::Sub, e_int(29)))])),
                    ],
                    vec![],
                    None,
                ),
                s_assign("hal", e_binop(e_var("hal"), BinOp::Add, e_binop(e_int(765433), BinOp::Mul, e_index(e_var("months"), e_var("my"))))),
                s_assign("day", e_binop(e_var("day"), BinOp::Add, e_call("intdiv", vec![e_var("hal"), e_int(25920)]))),
                s_assign("hal", e_binop(e_var("hal"), BinOp::Mod, e_int(25920))),
                s_assign("t1a", e_static_call("DateTime", "__elephc_jew_tishri1", vec![e_binop(e_binop(e_var("my"), BinOp::Add, e_int(1)), BinOp::Mod, e_int(19)), e_var("day"), e_var("hal")])),
            ],
            vec![],
            Some(vec![
            s_assign("py", e_binop(e_binop(e_var("mc"), BinOp::Mul, e_int(19)), BinOp::Add, e_var("my"))),
            s_if(
                e_binop(e_var("inputDay"), BinOp::GtEq, e_binop(e_var("t1"), BinOp::Sub, e_int(177))),
                vec![
                    s_if(
                        e_binop(e_var("inputDay"), BinOp::Gt, e_binop(e_var("t1"), BinOp::Sub, e_int(30))),
                        vec![
                            s_return(e_array_assoc(vec![(e_str("y"), e_var("py")), (e_str("m"), e_int(13)), (e_str("d"), e_binop(e_binop(e_var("inputDay"), BinOp::Sub, e_var("t1")), BinOp::Add, e_int(30)))])),
                        ],
                        vec![],
                        None,
                    ),
                    s_if(
                        e_binop(e_var("inputDay"), BinOp::Gt, e_binop(e_var("t1"), BinOp::Sub, e_int(60))),
                        vec![
                            s_return(e_array_assoc(vec![(e_str("y"), e_var("py")), (e_str("m"), e_int(12)), (e_str("d"), e_binop(e_binop(e_var("inputDay"), BinOp::Sub, e_var("t1")), BinOp::Add, e_int(60)))])),
                        ],
                        vec![],
                        None,
                    ),
                    s_if(
                        e_binop(e_var("inputDay"), BinOp::Gt, e_binop(e_var("t1"), BinOp::Sub, e_int(89))),
                        vec![
                            s_return(e_array_assoc(vec![(e_str("y"), e_var("py")), (e_str("m"), e_int(11)), (e_str("d"), e_binop(e_binop(e_var("inputDay"), BinOp::Sub, e_var("t1")), BinOp::Add, e_int(89)))])),
                        ],
                        vec![],
                        None,
                    ),
                    s_if(
                        e_binop(e_var("inputDay"), BinOp::Gt, e_binop(e_var("t1"), BinOp::Sub, e_int(119))),
                        vec![
                            s_return(e_array_assoc(vec![(e_str("y"), e_var("py")), (e_str("m"), e_int(10)), (e_str("d"), e_binop(e_binop(e_var("inputDay"), BinOp::Sub, e_var("t1")), BinOp::Add, e_int(119)))])),
                        ],
                        vec![],
                        None,
                    ),
                    s_if(
                        e_binop(e_var("inputDay"), BinOp::Gt, e_binop(e_var("t1"), BinOp::Sub, e_int(148))),
                        vec![
                            s_return(e_array_assoc(vec![(e_str("y"), e_var("py")), (e_str("m"), e_int(9)), (e_str("d"), e_binop(e_binop(e_var("inputDay"), BinOp::Sub, e_var("t1")), BinOp::Add, e_int(148)))])),
                        ],
                        vec![],
                        None,
                    ),
                    s_return(e_array_assoc(vec![(e_str("y"), e_var("py")), (e_str("m"), e_int(8)), (e_str("d"), e_binop(e_binop(e_var("inputDay"), BinOp::Sub, e_var("t1")), BinOp::Add, e_int(178)))])),
                ],
                vec![],
                None,
            ),
            s_if(
                e_binop(e_index(e_var("months"), e_binop(e_binop(e_var("py"), BinOp::Sub, e_int(1)), BinOp::Mod, e_int(19))), BinOp::Eq, e_int(13)),
                vec![
                    s_assign("pm", e_int(7)),
                    s_assign("pd", e_binop(e_binop(e_var("inputDay"), BinOp::Sub, e_var("t1")), BinOp::Add, e_int(207))),
                    s_if(
                        e_binop(e_var("pd"), BinOp::Gt, e_int(0)),
                        vec![
                            s_return(e_array_assoc(vec![(e_str("y"), e_var("py")), (e_str("m"), e_var("pm")), (e_str("d"), e_var("pd"))])),
                        ],
                        vec![],
                        None,
                    ),
                    s_assign("pm", e_binop(e_var("pm"), BinOp::Sub, e_int(1))),
                    s_assign("pd", e_binop(e_var("pd"), BinOp::Add, e_int(30))),
                    s_if(
                        e_binop(e_var("pd"), BinOp::Gt, e_int(0)),
                        vec![
                            s_return(e_array_assoc(vec![(e_str("y"), e_var("py")), (e_str("m"), e_var("pm")), (e_str("d"), e_var("pd"))])),
                        ],
                        vec![],
                        None,
                    ),
                    s_assign("pm", e_binop(e_var("pm"), BinOp::Sub, e_int(1))),
                    s_assign("pd", e_binop(e_var("pd"), BinOp::Add, e_int(30))),
                ],
                vec![],
                Some(vec![
                s_assign("pm", e_int(7)),
                s_assign("pd", e_binop(e_binop(e_var("inputDay"), BinOp::Sub, e_var("t1")), BinOp::Add, e_int(207))),
                s_if(
                    e_binop(e_var("pd"), BinOp::Gt, e_int(0)),
                    vec![
                        s_return(e_array_assoc(vec![(e_str("y"), e_var("py")), (e_str("m"), e_var("pm")), (e_str("d"), e_var("pd"))])),
                    ],
                    vec![],
                    None,
                ),
                s_assign("pm", e_binop(e_var("pm"), BinOp::Sub, e_int(2))),
                s_assign("pd", e_binop(e_var("pd"), BinOp::Add, e_int(30))),
            ]),
            ),
            s_if(
                e_binop(e_var("pd"), BinOp::Gt, e_int(0)),
                vec![
                    s_return(e_array_assoc(vec![(e_str("y"), e_var("py")), (e_str("m"), e_var("pm")), (e_str("d"), e_var("pd"))])),
                ],
                vec![],
                None,
            ),
            s_assign("pm", e_binop(e_var("pm"), BinOp::Sub, e_int(1))),
            s_assign("pd", e_binop(e_var("pd"), BinOp::Add, e_int(29))),
            s_if(
                e_binop(e_var("pd"), BinOp::Gt, e_int(0)),
                vec![
                    s_return(e_array_assoc(vec![(e_str("y"), e_var("py")), (e_str("m"), e_var("pm")), (e_str("d"), e_var("pd"))])),
                ],
                vec![],
                None,
            ),
            s_assign("t1a", e_var("t1")),
            s_assign("f2", e_static_call("DateTime", "__elephc_jew_find_tishri_molad", vec![e_binop(e_var("day"), BinOp::Sub, e_int(365))])),
            s_assign("mc", e_index(e_var("f2"), e_str("mc"))),
            s_assign("my", e_index(e_var("f2"), e_str("my"))),
            s_assign("day", e_index(e_var("f2"), e_str("md"))),
            s_assign("hal", e_index(e_var("f2"), e_str("mh"))),
            s_assign("t1", e_static_call("DateTime", "__elephc_jew_tishri1", vec![e_var("my"), e_var("day"), e_var("hal")])),
        ]),
        ),
        s_assign("yl", e_binop(e_var("t1a"), BinOp::Sub, e_var("t1"))),
        s_assign("day", e_binop(e_binop(e_var("inputDay"), BinOp::Sub, e_var("t1")), BinOp::Sub, e_int(29))),
        s_if(
            e_binop(e_binop(e_var("yl"), BinOp::Eq, e_int(355)), BinOp::Or, e_binop(e_var("yl"), BinOp::Eq, e_int(385))),
            vec![
                s_if(
                    e_binop(e_var("day"), BinOp::LtEq, e_int(30)),
                    vec![
                        s_return(e_array_assoc(vec![(e_str("y"), e_var("py")), (e_str("m"), e_int(2)), (e_str("d"), e_var("day"))])),
                    ],
                    vec![],
                    None,
                ),
                s_assign("day", e_binop(e_var("day"), BinOp::Sub, e_int(30))),
            ],
            vec![],
            Some(vec![
            s_if(
                e_binop(e_var("day"), BinOp::LtEq, e_int(29)),
                vec![
                    s_return(e_array_assoc(vec![(e_str("y"), e_var("py")), (e_str("m"), e_int(2)), (e_str("d"), e_var("day"))])),
                ],
                vec![],
                None,
            ),
            s_assign("day", e_binop(e_var("day"), BinOp::Sub, e_int(29))),
        ]),
        ),
        s_return(e_array_assoc(vec![(e_str("y"), e_var("py")), (e_str("m"), e_int(3)), (e_str("d"), e_var("day"))])),
    ]
}

/// Reproduces `SDN_TO_JUL_SRC`.
pub(super) fn sdn_to_jul() -> Vec<Stmt> {
    vec![
        s_if(
            e_binop(e_var("sdn"), BinOp::LtEq, e_int(0)),
            vec![
                s_return(e_array_assoc(vec![(e_str("y"), e_int(0)), (e_str("m"), e_int(0)), (e_str("d"), e_int(0))])),
            ],
            vec![],
            None,
        ),
        s_assign("temp", e_binop(e_binop(e_var("sdn"), BinOp::Mul, e_int(4)), BinOp::Add, e_binop(e_binop(e_int(32083), BinOp::Mul, e_int(4)), BinOp::Sub, e_int(1)))),
        s_assign("year", e_call("intdiv", vec![e_var("temp"), e_int(1461)])),
        s_assign("doy", e_binop(e_call("intdiv", vec![e_binop(e_var("temp"), BinOp::Mod, e_int(1461)), e_int(4)]), BinOp::Add, e_int(1))),
        s_assign("temp", e_binop(e_binop(e_var("doy"), BinOp::Mul, e_int(5)), BinOp::Sub, e_int(3))),
        s_assign("month", e_call("intdiv", vec![e_var("temp"), e_int(153)])),
        s_assign("day", e_binop(e_call("intdiv", vec![e_binop(e_var("temp"), BinOp::Mod, e_int(153)), e_int(5)]), BinOp::Add, e_int(1))),
        s_if(
            e_binop(e_var("month"), BinOp::Lt, e_int(10)),
            vec![
                s_assign("month", e_binop(e_var("month"), BinOp::Add, e_int(3))),
            ],
            vec![],
            Some(vec![
            s_assign("year", e_binop(e_var("year"), BinOp::Add, e_int(1))),
            s_assign("month", e_binop(e_var("month"), BinOp::Sub, e_int(9))),
        ]),
        ),
        s_assign("year", e_binop(e_var("year"), BinOp::Sub, e_int(4800))),
        s_if(
            e_binop(e_var("year"), BinOp::LtEq, e_int(0)),
            vec![
                s_assign("year", e_binop(e_var("year"), BinOp::Sub, e_int(1))),
            ],
            vec![],
            None,
        ),
        s_return(e_array_assoc(vec![(e_str("y"), e_var("year")), (e_str("m"), e_var("month")), (e_str("d"), e_var("day"))])),
    ]
}

/// Reproduces `UNIXTOJD_SRC`.
pub(super) fn unixtojd() -> Vec<Stmt> {
    vec![
        s_assign("y", e_call("intval", vec![e_call("gmdate", vec![e_str("Y"), e_var("timestamp")])])),
        s_assign("m", e_call("intval", vec![e_call("gmdate", vec![e_str("n"), e_var("timestamp")])])),
        s_assign("d", e_call("intval", vec![e_call("gmdate", vec![e_str("j"), e_var("timestamp")])])),
        s_return(e_static_call("DateTime", "__elephc_greg_to_sdn", vec![e_var("y"), e_var("m"), e_var("d")])),
    ]
}
